### ISSUE TITLE
Keyerror: 'events' ao tentar nu.authenticate(user, passwd)

### ISSUE THREAD

**Issue by LucasBeneti** [andreroggeri/pynubank#101]
Ao seguir o próprio código do README, pra autenticar e pegar as contas anteriores. O código utilizado foi o seguinte:
``` python
import os
from pynubank import Nubank

user = os.getenv('NU_USER')
passwd = os.getenv('NU_PASSWD')

nu = Nubank()
nu.authenticate(user, passwd)

bills = nu.get_bills()
print(len(bills))
```
O que resultou no seguinte erro:
```bash
Traceback (most recent call last):
  File "accounting.py", line 11, in <module>
    nu.authenticate(user, passwd)
  File "/Users/lucas/miniconda3/envs/accounting/lib/python3.6/site-packages/pynubank/nubank.py", line 79, in authenticate
    self.feed_url = data['_links']['events']['href']
KeyError: 'events'
```
Usei o pacote instalando via pip.

**Comment by carlosdaniiel07** [comment]
O erro se deve ao fato do Nubank obrigar a autenticação com QR Code (see #97).

**Comment by andreroggeri** [comment]
Está relacionado a #97, consegue testar com a versão 1.0.1?

**Comment by maronezzi** [comment]
Conseguiram algum avanço? Não consegui fazer funcionar em nenhuma das duas versões.

**Comment by henriqueortiz** [comment]
Eu consegui com a versão 1.0.1
só precisa validar o qrcode e depois foi tranquilo.

Att

Em qui., 20 de fev. de 2020 às 15:31, maronezzi <notifications@github.com>
escreveu:

**Comment by carlosdaniiel07** [comment]
> Conseguiram algum avanço? Não consegui fazer funcionar em nenhuma das duas versões.

Para funcionar voltei o repositório para versão 1.0.1 e segui exatamente a documentação abaixo (vale ressaltar que para que a autenticação seja feita com sucesso é necessário ler o QR Code que é printado no console com o app do Nubank):

``` python
from pynubank import Nubank

nu = Nubank()
uuid, qr_code = nu.get_qr_code()
# Nesse momeento será printado o QRCode no console
# Você precisa escanear pelo o seu app do celular
# Esse menu fica em NU > Perfil > Acesso pelo site
qr_code.print_ascii(invert=True)
input('Após escanear o QRCode pressione enter para continuar')
# Somente após escanear o QRCode você pode chamar a linha abaixo
nu.authenticate_with_qr_code('123456789', 'senha', uuid)
print(nu.get_account_balance())
```

**Comment by LucasBeneti** [comment]
> > Conseguiram algum avanço? Não consegui fazer funcionar em nenhuma das duas versões.
> 
> Para funcionar voltei o repositório para versão 1.0.1 e segui exatamente a documentação abaixo (vale ressaltar que para que a autenticação seja feita com sucesso é necessário ler o QR Code que é printado no console com o app do Nubank):
> 
> ```python
> from pynubank import Nubank
> 
> nu = Nubank()
> uuid, qr_code = nu.get_qr_code()
> # Nesse momeento será printado o QRCode no console
> # Você precisa escanear pelo o seu app do celular
> # Esse menu fica em NU > Perfil > Acesso pelo site
> qr_code.print_ascii(invert=True)
> input('Após escanear o QRCode pressione enter para continuar')
> # Somente após escanear o QRCode você pode chamar a linha abaixo
> nu.authenticate_with_qr_code('123456789', 'senha', uuid)
> print(nu.get_account_balance())
> ```

Eu não tinha me ligado desse esquema do QR code, teu código funcionou certinho.
Desculpa a demora de resposta e obrigado pela ajuda pessoal.

**Comment by andreroggeri** [comment]
Publiquei uma versão 1.2.0 que exatamente a mesma coisa que a 1.0.1. 

Assim não gera essa confusão pra quem tá chegando...
