### ISSUE TITLE
Desativar QRCode

### ISSUE THREAD

**Issue by makdisse** [andreroggeri/pynubank#109]
Ola,
O readme do projeto diz: 

> Caso a autenticação por QRCode esteja ativada na sua conta

Isso da a entender que é possivel desativar esse tipo de autenticacao. 
Meu entendimento esta correto? Se sim, tem como mencionar no readme como desativar?

Obrigado

**Comment by Lrcezimbra** [comment]
O q o README quer dizer é "Caso vc tenha sido o sorteado com o QR Code" kkkkk.

O QR Code não é habilitado para todos, mas isso é definido pela empresa. Não existe uma forma do usuário desativa-lo

**Comment by makdisse** [comment]
Entendi, obrigado.
Entao nao existe nenhum modo de rodar o script em daemon certo?
Meu plano era pegar as transacoes e trabalhar com elas no telegram.

**Comment by andreroggeri** [comment]
Isso, está escrito dessa forma pois no começo o QRCode não era necessário, daí foi ativando em fases pra todo mundo.
Acredito que hoje todas as contas tenham QRCode.

Uma alternativa pra rodar em script, seria gerar o token uma vez e mantê-lo salvo.
Se não me engano é possível fazer um "refresh" do token, porém hoje isso não é implementado pela lib (Mas PR são super bem vindos...)

**Comment by makdisse** [comment]
@andreroggeri existe algum exemplo online onde posso ver a implementacao de reusar um token salvo?

**Comment by makdisse** [comment]
Encontrei o modo como fazer funcionar sem precisar escanear o QRCode toda vez. Esta funcionando para mim ate agora, nao sei se eles forçam a expiracao do token.

Para quem precisar fazer o mesmo:

- Rode o python na mao e execute:

```
from pynubank import Nubank 
nu = Nubank()
uuid, qr_code = nu.get_qr_code()
qr_code.print_ascii(invert=True)
nu.authenticate_with_qr_code('22571269801', 'persist3ncia', uuid)
```
- Digite os comandos seguintes e copie os valores para um arquivo no formato `nu.PROP = VALOR`

```
nu.headers
nu.feed_url
nu.query_url
nu.bills_url
```

Pronto.

No seu arquivo final voce tera algo tipo:

```
from pynubank import Nubank
nu = Nubank()
nu.headers = {'Content-Type': 'application/json', ...}
nu.feed_url = 'https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/...'
nu.query_url = 'https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/...'
nu.bills_url = 'https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/...'
nu.get_account_balance()
```

**Comment by andreroggeri** [comment]
@makdisse estava repassando por essa thread e vi que vc comentou o seu cpf e senha do Nubank :~

Eu já apaguei aqui do github, mas quem está na thread recebeu por email. Recomendo vc trocar a senha pra evitar a dor de cabeça (Alguém mal intencionado pode cancelar seu cartão)
