### ISSUE TITLE
Obter detalhes de faturas futuras

### ISSUE THREAD

**Issue by Gulier** [andreroggeri/pynubank#112]
Boa noite, pessoal!

Estou montando algumas análises sobre faturas e esbarrei Em um problema discutido anteriormente sobre as faturas com o estado '`state': 'future'`, visto que o `get_bill_details` retorna `KeyError` para as faturas que não estão com status `'state': 'open'.`

Alguém já conseguiu uma solução para este cenário? Tentei dar algumas vasculhadas nos links mas tive certa dificuldade com essa situação específica...

**Comment by coutoreis** [comment]
@Gulier chegou a avançar algo neste sentido?

Estou pra começar a mexer aqui no código no final deste mês. Só instalei e fiz alguns requests até hoje. Este feat é algo que eu vou precisar. Se não tiver avançado vou dar uma olhada.

**Comment by andreroggeri** [comment]
Acredito que não seja muito complicado. Eu não consigo fazer pq não tenho nada parcelado pra olhar como vem o JSON.

Mas daria pra olhar as requisições no proprio site.

**Comment by Gulier** [comment]
Oi pessoal, não cheguei a olhar com maiores detalhes devido a algumas questões pessoais. Posso tentar disponibilizar o JSON algum desses dias para ajudar com a solução, se acharem interessante! Abs!
