### ISSUE TITLE
Dúvida - geração de boletos

### ISSUE THREAD

**Issue by cobap** [andreroggeri/pynubank#113]
Existe algum dos endpoints que permite geração de cobrança? Igual vemos pelo App. Retornando qrcode + link

Procurei no fórum do nubank e aqui nos issues mas não achei nada

**Comment by andreroggeri** [comment]
Existe sim @cobap , mas antes de conseguir acessar essa feature, precisariamos replicar a parte de autenticação igual ao app do celular (Troca de certificados, autorização por um dispositivo confiável, etc). Pois hoje a autenticação que usamos é a mesma do site, e ela só tem acesso leitura das coisas por ser menos confiável.

O caminho seria analisar as requisições que o app faz e tentar fazer igual, mas acho que vai ser um pouco dificil.

Se alguém estiver disposto a seguir por esse caminho e abrir um PR poderiamos incluir isso nessa lib.

**Comment by cobap** [comment]
Alguma sugestão de como acompanhar as requisições via app? Tenho android e windows, talvez exista uma forma de emular app e fazer engenharia reversa? Posso tentar algo aqui

**Comment by andreroggeri** [comment]
Eu fiz algo parecido para obter os endpoints e querys da NuConta.

Não tenho mais o ambiente em meu computador, mas fiz uma engenharia reversa parecida.
Não se o network profiler do android studio vai funcionar com um app de produção (Mas não custa tentar)

O que eu fiz foi utilizar um proxy (No windows utilizei o Fiddler) e configurei o emulador para utilizar esse proxy.

Além disso o Nubank implementa [certificate pinning](https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning) então o trafego dele não conseguia ser descriptografado pelo Fiddler. Para resolver isso usei a ferramenta [frida](https://frida.re/) para injetar um código que fizesse o bypass do pinning. (Segui algum tutorial como [esse](https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29) e funcioou)

**Comment by cobap** [comment]
É, vai ser meio complicado... não manjo muito de networking. Vou esperar sobrar um tempo livre aqui e tento fazer algo. Se quiser deixar o issue fechado, eu aviso se conseguir algo! 👍

**Comment by andreroggeri** [comment]
@cobap Eu consegui fazer esse fluxo de autenticação como se fosse o app na #120  :tada: 
![image](https://user-images.githubusercontent.com/6232673/84075480-9b1b1800-a9aa-11ea-83da-c3103ff4c0b1.png)

O duro agora é que eu não estou conseguindo enxergar as requisições depois que faz o login... mas pretendo dar uma olhada nisso depois

**Comment by cobap** [comment]
Que animal!! Mandou bem. Ainda é aquele mesmo software de sniffing p/ acompanhar as requisições? Se estivesse simulando via web pelo chrome não ficava mais fácil (talvez esteja confundindo as coisas aqui).

Outra coisa, vi que o #120 ainda não foi pro master. Ta com data pro novo release, ou terminar de completar todo esse fluxo antes?

**Comment by andreroggeri** [comment]
Isso aí, foi utilizando o fiddler pra entender o fluxo das requisições e também descompilei o app pra entender como que estava funcionando. =]

Falta um ajuste pra mergear a #120 e liberar um beta, que é adicionar o o `cli` como binário. Acredito que amanhã eu consiga terminar isso

**Comment by andreroggeri** [comment]
@cobap tava olhando aqui e vi que cobrança != boleto.

Gerar o link e o QRCode tá super fácil agora, mas não é a mesma coisa que gerar o boleto.
Qual das duas coisas vc queria fazer ?

**Comment by cobap** [comment]
Então, fui dar uma olhada agora no app, e vi que na nova versão p/ Android a função cobrar não aparece mais. Agora vem igual imagem abaixo:

![nubank_features](https://user-images.githubusercontent.com/6344807/84527165-5518c980-acb4-11ea-97b7-20bbb788c4fd.jpeg)
![nubank_features2](https://user-images.githubusercontent.com/6344807/84527234-5a761400-acb4-11ea-9a44-fb6bfac1e00e.jpeg)

**Comment by cobap** [comment]
Não sei como ficou a versão que vc esta simulando, mas se chegarmos nessa parte de geração de boleto + valor => código. Isso já resolve demais meu problema, pq terei o código do boleto. Btw, não consegui achar nessa nova versão a função "Cobrar". Eu só vejo a função "Depositar" agora, que lista essas 3 opções da imagem acima

**Comment by andreroggeri** [comment]
Aqui a funcionalidade de cobrar ainda aparece na tela inicial do app.
![image](https://user-images.githubusercontent.com/6232673/84532676-058acb80-acbd-11ea-8ee2-77daacb0a721.png)

Mas ele gera um QRCode que leva pro site do Nubank com os dados da sua conta pra fazer transferência (Sem boleto). Isso eu consegui fazer, e é bem fácil.

Agora pra gerar o boleto tem que ser por esse caminho aí que vc mandou.
Mas olhando as requisições do app, ainda não entendi como que ele gera esse número do boleto, pq aparentemente ele só muda os números do final (Que é o valor do boleto).

**Comment by cobap** [comment]
Também pensei que o o código de barras fosse igual, mas tem diferença minima. Gerei um boleto de 60, mudei na mão para 120, e depois gerei o mesmo boleto de 120: 

![image](https://user-images.githubusercontent.com/6344807/84535427-2d306280-acc2-11ea-8403-3af39f96a061.png)

**Comment by cobap** [comment]
Pelo que entendi, você não consegue acessar o código de barras gerado, só direcionar o link para cobrança nubank <-> nubank

**Comment by andreroggeri** [comment]
Hmmm... Bem observado sobre os números do boleto.

Preciso olhar então se ele é gerado com algum dado gerado em outro lugar.

**Comment by cobap** [comment]
Andre, ótimas notícias! Eu gerei os links de boleto aqui, o código de barras ficou 100% igual. Agora só precisava confirmar algumas coisas:

- Se existe uma mudança no código de barras do boleto em um período mais longo que "dias" (pode mudar por semana ou mês - inclusive estou com um leve receio que tenha gerado o mesmo código p/ mim por fazer os testes durante fds)

- Existe algum forma fácil de resgatar o código do boleto gerado? Eu poderia só embedar direto o código que é gerado aqui pra mim, mas não parece nada escalável

- Entender a possível lógica para os números intermediários do código de barras, assim podemos gerar código para qql valor sem precisar gerar na mão antes.

O que acha?

**Comment by cobap** [comment]
Só um update @andreroggeri , dei uma pesquisada sobre a geração do código dos boletos, acho que não vou conseguir seguir esse caminho... 

Achei esse documento que explica como os códigos são gerado, sei que eles mudam com padrões que não dá para prever:
bb.com.br/docs/pub/emp/empl/dwn/Doc5175Bloqueto.pdf

![image](https://user-images.githubusercontent.com/6344807/84705991-a7ffb480-af32-11ea-824a-317a13ccfcfb.png)

Acho que a última opção é se tivesse uma forma de copiar esse código gerado pelo nubank, resolveria todos os problemas. Você chegou na parte que ele gera o código do boleto?

**Comment by andreroggeri** [comment]
Acredito que achei o request que gera o boleto =]

Vou fazer uns testes aqui e já retorno

**Comment by andreroggeri** [comment]
@cobap deu certo, a PR #126 adiciona o método `create_boleto` que gera a linha digitável pra vc.

Eu dei uma olhada rápida e não achei nada pronto pra gerar o código de barras a partir dos números. (Me parece que os boletos do BR tem um padrão especifico chamado "código 25").

Isso já te atende ?

**Comment by cobap** [comment]
Vi o código, ta perfeito! A questão do código de barras, não tem problema, só com os números já consigo fazer a cobrança como imaginava.

Ajudou demais Andre, você é fera. Obg por todo o suporte

**Comment by andreroggeri** [comment]
Beleza, publiquei a versão 2.1.0 com essa feature então :rocket:

**Comment by X-C0DE** [comment]
Fiquei com uma dúvida quando essa geração do boleto. Porque tipo assim, pra gerar pra nuconta só pode a partir de 20 reais, certo?
Eu testei gerar um aqui com o valor 17 e passou de boa. Nesse caso, o valor é pra cair na Nuconta ou como pagamento de adiantamento de uma fatura atual?
Quando ao valor, se eu informar apenas 17, será R$ 17,00 mesmo?
Estou começando a mexer recentemente e percebi que os valores contidos nos JSON possuem uma formatação um pouco diferente. Ex: R$ 199,53 -> 19953

**Comment by andreroggeri** [comment]
@X-C0DE sobre o valor, talvez o bloqueio esteja só no app, mas o backend deles não bloqueia (Mas acho bom não abusar 😆 )

Esse boleto é o boleto para deposito na NuConta, não é o boleto de pagamento da fatura.

Sobre o valor, que eu me lembre sim, @cobap vc chegou a usar essa feature ? Sabe se o valor é inteiro (Ex: `create_boleto(15)` vai gerar um boleto de R$15,00 ?)

**Comment by X-C0DE** [comment]
> @X-C0DE sobre o valor, talvez o bloqueio esteja só no app, mas o backend deles não bloqueia (Mas acho bom não abusar laughing )
> 
> Esse boleto é o boleto para deposito na NuConta, não é o boleto de pagamento da fatura.
> 
> Sobre o valor, que eu me lembre sim, @cobap vc chegou a usar essa feature ? Sabe se o valor é inteiro (Ex: `create_boleto(15)` vai gerar um boleto de R$15,00 ?)

Obrigado pela atenção amigo. Sendo pra NuConta fica massa, pq dessa forma conseguirei gerar boletos com menos de R$ 20,00 kkkk Antes eu ia na fatura e gerava um boleto com valor personalizado 
Outra dúvida rápida. Sou de certa forma iniciante no python e estou procurando a melhor forma de formatar os valores em R$ que recebemos nos JSON's
Exemplo: Valor recebido: 101355. Valor que eu quero formatar: R$ 1.013,55

**Comment by andreroggeri** [comment]
kkkkk, é, mas é bom ficar de olho que eles podem reclamar.

Pra formatar os valores, acho que vc pode usar o `locale`

```
import locale

locale.setlocale(locale.LC_ALL, 'pt_BR')

valor = 101355
locale.currency(valor/100, grouping=True) # Vai retornar 'R$ 1.013,55'

```
