### ISSUE TITLE
Opção de mock por configuração

### ISSUE THREAD

**Issue by joubertredrat** [andreroggeri/pynubank#124]
Bom dia a todos.

Estou querendo usar esta lib para um projeto, mas para evitar essas tretas de bloqueio eu estava pensando se não seria interessante a lib ter suporte a mock dentro dela mesmo como no exemplo abaixo:

```python
nu = NubankMock()
uuid, qr_code = nu.get_qr_code()
nu.authenticate_with_qr_code('123456789', 'senha', uuid)
card_statements = nu.get_card_statements()
```

Acredito eu que dessa forma fica mais fácil para as pessoas implementarem seus apps ou mvp e após tudo estar funcionando, aí o mock seria substituido pela requisição real, o que acham?

**Comment by andreroggeri** [comment]
Acho legal essa ideia. 

Tava pensando aqui, a classe HttpClient é quem faz as chamadas externas. Ele poderia ser um parâmetro do construtor da classe Nubank, e poderíamos criar um MockHttpClient. Mas ainda não pensei como decidir qual mock retornar. 

Anyway, se vc quiser fazer um PR com qualquer uma das ideias eu topo incorporar na lib 🤘
