### ISSUE TITLE
Adicionar endpoint para detalhes da fatura

### ISSUE THREAD

**Issue by janjitsu** [andreroggeri/pynubank#13]
Olá! Gostaria de obter os detalhes da fatura. Até já implementei isso, porém tenho dúvidas sobre a melhor forma de implementação, uma forma simples seria:

```
def get_bill_details(self, bill):
    request = requests.get(bill['_links']['self']['href'], headers=self.headers)
    return json.loads(request.content.decode('utf-8'))
```

`bill` seria um elemento do array retornado por `get_card_bills()` mas talvez fica estranho passar para a função elementos de um resultado de uma response externa, talvez o resultado poderia se tornar um array de elementos definidos na aplicação, algo como: 
```
class Bill
    (...)
```

Gostaria de umas dicas pois não tenho muita experiência com python profissionalmente, quais as melhores práticas, etc talvez links de projetos interessantes para seguir. #ajudaluciano

**Comment by andreroggeri** [comment]
Fala @janjitsu !

Na minha opinião, essa lib deve ser o mais simples o possível. Mapear os retornos da API numa classe, facilitaria o desenvolvimento por conta dos hints da IDE, mas acho que não compensa o esforço, já que o retorno do extrato da conta e lançamentos do cartão também não estão mapeados. Além disso qualquer mudança na API teria que ser feita uma mudança no pynubank também.

Por curiosidade, qual o seu caso de uso para precisar dos detalhes da fatura ? Talvez seja possível obter o mesmo dado fazendo uma consulta graphql.

PS: Eu também tenho pouca experiência com python, sou entusiasta ! 😄

**Comment by janjitsu** [comment]
Opa @andreroggeri ! 

Então o caso de uso é o seguinte:

Nós sabemos que os relatórios do nubank são bem limitados (ou simples).
O que faz todo o sentido pra o tipo de cliente que eles tem como público alvo.

Eu desejo categorizar os gastos de uma fatura, tanto por categoria quanto por tags.

Ao requisitar todas as transações (`get_card_feed`) eu recebo todas as transações com detalhes (categoria, tags etc) porém eu não sei dizer em que fatura elas estão.

Ao requisitar o sumário de faturas (`get_card_bills`) eu recebo uma lista com o sumário das faturas, me dizendo quanto custou cada fatura e se ja foi paga ou não, e um link para os detalhes da fatura (#13)

nos detalhes da fatura eu recebo uma informação limitada sobre cada linha da fatura. A minha idéia é casar esses dados com o card_feed e assim eu conseguirei categorizar a fatura da mesma forma que o feed.

Tentei explorar a graphql mas não vi uma maneira de acessar as faturas similar a rest API. Me pareceu que a graphql é mais focada na Nuconta...

Voltando então pra pergunta da implementação, a sugestão acima então está de bom tamanho?

**Comment by andreroggeri** [comment]
Bem legal, você tá desenvolvendo algo open source ? Se sim me passa o link que quero ver depois. 


Acho que a primeira opção é mais simples e o suficiente. Só adicione um exemplo no readme de como pegar os detalhes da fatura ok ? 👌

**Comment by janjitsu** [comment]
Sim, github.com/janjitsu/nuflow

Mais tarde eu faço um PR! Valeu!

**Comment by vctrd** [comment]
Ele mostra sim (por exemplo quando existir compras parceladas), parece que ele não da as informações do mesmo jeito, mas exitem as informações. Vou procurar e informo vocês se consigo encontrar algo.

Obrigado
Abraços

**Comment by Gulier** [comment]
Boa noite, pessoal!

Estou montando algumas análises sobre faturas e esbarrei nessa última questão levantada pelo @vctrd sobre as faturas com o estado `'state': 'future'`, visto que o `get_bill_details` retorna `KeyError` para as faturas que não estão com status `'state': 'open'`.

Alguém já conseguiu uma solução para este cenário?

**Comment by andreroggeri** [comment]
Infelizmente eu não consigo ajudar nesse caso pq não tenho nada parcelado pra ver os dados futuros.

Teria que olhar no site do nubank como que ele monta as faturas futuras, pra replicarmos aqui.

@Gulier talvez valha uma issue separada pra esse caso não ?

**Comment by Gulier** [comment]
De fato, @andreroggeri! Vou abrir um separado aqui agora, queria só conferir se alguém já tinha encontrado um caminho
