### ISSUE TITLE
NuRequestException: The request made failed with HTTP status code 403

### ISSUE THREAD

**Issue by coutoreis** [andreroggeri/pynubank#131]
Ao rodar o código de exemplo abaixo recebo erro 403 (forbidden). 

```
from pynubank import Nubank
nu = Nubank()
uuid, qr_code = nu.get_qr_code()
qr_code.print_ascii(invert=True)
input('Após escanear o QRCode pressione enter para continuar')
nu.authenticate_with_qr_code('XXXXXXXXXX', 'YYYYYYYYYY', uuid)
```

Executo via Jupyter, escaneio o QR Code e teclo ENTER. Em seguida recebo o erro.

Não está claro pra mim se estou fazendo algo errado.

**Comment by andreroggeri** [comment]
Fala @coutoreis !

Cara, eu imagino que o app tá lendo o QRCode incorretamente.

Eu fiz um teste aqui e tb deu problema no Jupyter.
O que vc pode fazer, é gerar uma imagem no lugar de printar o qrcode em ascii.

Primeiro vc precisa instalar o Pillow: `pip install Pillow`

Depois você substitui o trecho que exibe o qrcode por `qr_code.make_image()`

Dessa maneira deu certo aqui.

![image](https://user-images.githubusercontent.com/6232673/87426320-5c820a00-c5b5-11ea-920a-5f5716891046.png)

**Comment by coutoreis** [comment]
@andreroggeri , obrigado pelo retorno. Faz sentido sua sugestão. Hoje à noite vou testar.

**Comment by coutoreis** [comment]
@andreroggeri , erro permanece acontecendo. Rodando direto pelo terminal funciona.

```
---------------------------------------------------------------------------
NuRequestException                        Traceback (most recent call last)
 in 
----> 1 nu.authenticate_with_qr_code('XXXXXXXX', 'YYYYYYYYYY', uuid)

C:\ProgramData\Anaconda3\lib\site-packages\pynubank\nubank.py in authenticate_with_qr_code(self, cpf, password, uuid)
     70 
     71     def authenticate_with_qr_code(self, cpf: str, password, uuid: str):
---> 72         auth_data = self._password_auth(cpf, password)
     73         self.client.set_header('Authorization', f'Bearer {auth_data["access_token"]}')
     74 

C:\ProgramData\Anaconda3\lib\site-packages\pynubank\nubank.py in _password_auth(self, cpf, password)
     55             "client_secret": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
     56         }
---> 57         return self.client.post(self.discovery.get_url('login'), json=payload)
     58 
     59     def _save_auth_data(self, auth_data: dict) -> None:

C:\ProgramData\Anaconda3\lib\site-packages\pynubank\utils\http.py in post(self, url, json)
     36 
     37     def post(self, url: str, json: dict) -> dict:
---> 38         return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))

C:\ProgramData\Anaconda3\lib\site-packages\pynubank\utils\http.py in _handle_response(self, response)
     28     def _handle_response(self, response: Response) -> dict:
     29         if response.status_code != 200:
---> 30             raise NuRequestException(response)
     31 
     32         return response.json()

NuRequestException: The request made failed with HTTP status code 403
```

**Comment by andreroggeri** [comment]
Acabei encontrando o bug que vc está passando, em um lugar estava usando variável de classe e estava mantendo um estado incorreto. Isso era mais provável de acontecer no Jupyter pq ele mantem rodando, então simplesmente instanciar uma nova classe do Nubank estava mantendo um token antigo.

Fiz o deploy da versão 2.1.1, você pode testar para ver se resolveu ?

**Comment by coutoreis** [comment]
Faz todo o sentido sua análise. Funcionou perfeitamente, Andre. 

Obrigado.
