### ISSUE TITLE
QRCode Para Efetivar Transferência

### ISSUE THREAD

**Issue by vinidanger** [andreroggeri/pynubank#133]
Olá!

Venho através deste, solicitar/opinar sobre um sistema interessante.
Seria basicamente um QRCode para ser escaneado e efetivado uma transferência de Nubank para Nubank.

Seria algo como:
Gerar um QRCode com os dados da pessoa que irá receber o valor da transferência.
Para fazer a transferência, seria direto pelo App > Transferir > QRCode, e definir o valor a ser transferido.

Grato!

**Comment by andreroggeri** [comment]
@vinidanger nova versão 2.2.0 é possível gerar a url de pagamento ex: https://nubank.com.br/pagar/xxxxx/yyyyy.

Com essa url basta gerar um qrcode com essa url que o app do Nubank deve conseguir escanear.
