### ISSUE TITLE
[Conta PJ] Opção de gerar boleto

### ISSUE THREAD

**Issue by juliorodx** [andreroggeri/pynubank#139]
Falei com o suporte Nubank, porém, há muito tempo sempre a mesma resposta de "sem previsão". Vi que a atual API é para Pessoa Física. Há alguma possibilidade de API para conta CNPJ? Se houver algum endpoint ou liberação, gostaria de ajudar a desenvolver, por enquanto estou no aguardo deles.

**Comment by andreroggeri** [comment]
Fala Júlio, blz?

Cara honestamente eu não sei. Eu construí essa lib em cima das requisições que o app faz. 

Eu não sei se o app é o mesmo pra PJ, se for talvez seja fácil de replicar aqui, o problema é que eu não tenho conta PJ, entao não consigo implementar

**Comment by andreroggeri** [comment]
Se você topar, posso te passar o caminho das pedras de como olhar as requisições, vc vai precisar de um emulador Android ou um device Android com root.

**Comment by juliorodx** [comment]
@andreroggeri Ótimo, se quiser, pode me enviar sim, por enquanto, estou fazendo algumas análises, estava pensando em criar para JS também, para quem utiliza Node, assim como eu, para fazer as integrações.

**Comment by juliorodx** [comment]
Só pra dar um up aqui, eu pedi para meus colegas mandarem sugestão de API também, e o suporte disse que "sem previsão" ainda... quem sabe, só estou esperando isso para migrar todo meu serviço de recebimento em boleto para lá :D

**Comment by andreroggeri** [comment]
Po, acabei deixando vc no vácuo :disappointed: foi mal.


Acho que seria mais fácil marcarmos uma call para eu te mostrar como capturar as requisições do app.
Se topar me chama no email / chats para combinarmos => a.roggeri.c@gmail.com

**Comment by Ulisses1478** [comment]
vc pode gravar uma "aula" e disponibilizar no yt?

**Comment by matheusfelipeog** [comment]
> vc pode gravar uma "aula" e disponibilizar no yt?

Também acho interessante que grave uma "aula" mostrando esse processo de análise. Assim, fica mais fácil para novas pessoas que, assim como nós, também tem interesse, e também para você @andreroggeri, que não vai precisar marcar call com cada pessoa individualmente.

Faça isso, por favor 😆

**Comment by Ulisses1478** [comment]
> > vc pode gravar uma "aula" e disponibilizar no yt?
> 
> Também acho interessante que grave uma "aula" mostrando esse processo de análise. Assim, fica mais fácil para novas pessoas que, assim como nós, também tem interesse, e também para você @andreroggeri, que não vai precisar marcar call com cada pessoa individualmente.
> 
> Faça isso, por favor 😆

se vc ta mt interessado ele explica aq como ele fez.

https://github.com/andreroggeri/pynubank/issues/113

**Comment by matheusfelipeog** [comment]
> se vc ta mt interessado ele explica aq como ele fez.
> 
> #113

@Ulisses1478 , obrigado 😄

**Comment by andreroggeri** [comment]
Fala galera, mal a demora... Acabou caindo no meu esquecimento.

Vou deixar um guia aqui pra quem quiser analisar as requisições do Nubank.

**Pré Requisitos:**
Dispositivo / Emulador com Root
Burp Suite instalado para analisar as requisições
Aplicativo do Nubank instalado
Proxy do Android configurado apontando para o Burp Suite
[frida-server](https://github.com/frida/frida/releases) rodando no Android
[adb](https://developer.android.com/studio/releases/platform-tools) disponível no PATH

**Guia**
1. Fazer login no Nubank nesse dispositivo
2. Baixar o certificado gerado pelo login (Fica em /data/data/com.nu.production/files/{ID_DA_SUA_CONTA}/KeyStore.default.p12
o comando para copiar é `adb pull /data/data/com.nu.production/files/{ID_DA_SUA_CONTA}/KeyStore.default.p12`
3. Configurar o Burp Suite para utilizar o certificado do Nubank (A senha do certificado é **nubank**)
![image](https://user-images.githubusercontent.com/6232673/93383146-9b447280-f839-11ea-8a3b-3d6f2e3e8934.png)
4. Executar a aplicação pelo frida com o [script que desativa o certificate pinning](https://gist.github.com/andreroggeri/0926ff56c867e6826f250d559e8709c9)
`frida -U -f com.nu.production -l .\frida.js --no-pause`
5. Navegar pela a funcionalidade que vc quer replicar aqui no `pynubank`
O request deve aparecer no Burp Suite, e por lá é possível descobrir quais as querys são utilizadas para montar cada tela
![image](https://user-images.githubusercontent.com/6232673/93384130-03e01f00-f83b-11ea-9e0c-cfc1f4af42c3.png)

**Comment by andreroggeri** [comment]
Só dando um update aqui, o @uxmarinho me mostrou o insomnia aqui, e com ele dá pra ver a documentação da API.
![image](https://user-images.githubusercontent.com/6232673/101708477-12218e00-3a6c-11eb-8134-17ce7b65e670.png)


Talvez ajude quem estiver nessa jornada =]

**Comment by fmsouza** [comment]
@andreroggeri fantástico! Você poderia compartilhar também, por favor, como você fez pra ver o schema da API inteiro dessa forma? Basta só enviar uma requisição qualquer pelo Insomnia ou precisa configurar mais alguma coisa?

**Comment by rdsedmundo** [comment]
@fmsouza ele provavelmente enviou a query de "Schema Introspection", é só você colocar uma URL válida em um endpoint, clicar em Schema, e em Refresh Schema, e o Insomnia vai enviar ela automaticamente—e desde que esteja tudo configurado corretamente os headers de autorização, o Insomnia vai salvar o schema completo da API.

**Comment by fmsouza** [comment]
Oi @rdsedmundo, obrigado pela resposta! Eu não sabia que o GraphQL server do Nubank tinha Introspection habilitado em produção, muito bom saber!

No entanto, tentei fazer tanto usando o Insomnia quanto um outro pacote do Node.js que já tô mais acostumado a usar pra esse fim, e nenhum dos casos conseguiu me entregar o Schema. Acho que pode estar faltando algum "pulo do gato" aqui.

Eu fiz o seguinte:
1. Gerei um UUID
2. Autenticação com senha
3. Salvei a lista de endpoints públicos e privados que vem na resposta da autenticação
4. Busquei a URL para o endpoint `ghostflame`, que é o que sei que é um servidor GraphQL
5. Enviei uma requisição que eu já sei que funciona pra ele pelo Insomnia e vi o resultado sendo entregue com sucesso.
6. Apertei o botão "Refresh Schema" e recebi um erro 400, dizendo que não foi possível atualizar o Schema.

![image](https://user-images.githubusercontent.com/1396615/113515738-bc0db480-954c-11eb-961c-8bc4fdec0b12.png)

Será que você @rdsedmundo ou o @andreroggeri poderiam me dar uma luz aqui? :)

Obrigado, e feliz Páscoa pra vocês!

**Comment by rdsedmundo** [comment]
Aqui também parou de funcionar, provavelmente desativaram. Alguém da equipe deve estar inscrito no repositório. 👀 

Se você enviar uma query mais simples manualmente consegue ver que agora está retornando que os campos não existem.

```gql
{
  __schema {
    types {
      name
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'types' in type '__Schema' is undefined @ '__schema/types'",
      "locations": [
        {
          "line": 11,
          "column": 5
        }
      ],
      "extensions": {}
    }
  ]
}
```

**Comment by fmsouza** [comment]
@rdsedmundo é exatamente isso que ta aparecendo pra mim quando olhos os detalhes da resposta.

Uma pena, mas valeu a tentativa! haha

**Comment by leoelias023** [comment]
@andreroggeri qual emulador android você utilizou?

**Comment by andreroggeri** [comment]
API 26 (Android 6.0)

**Comment by andreroggeri** [comment]
Sobre o ID ele é retornado em algumas chamadas da API, mas é mais fácil listar as pastas ali dentro de files

**Comment by Ulisses1478** [comment]
Não sei se ajuda mas eu usei a api 29 android 10

**Comment by leoelias023** [comment]
> Vc fez login na sua conta ? Acredito que só seja criado depois que o login for feito...

@andreroggeri  Fiz sim, estou emulando com a mesma versão da API (API 26 (Android 6.0)) (porém não possui ROOT)

Estou com dificuldade para tornar em modo ROOT e acessar os serviços do Google Play para instalar o app do Nu, vocês sugerem algum artigo? 

Quando seleciono um aparelho com `Google Play Services` ele não deixa eu utilizar o `adb root`.

**Comment by andreroggeri** [comment]
Pra ter acesso root vc precisa usar o emulador que não tem os aplicativos do google, vc instala eles dps com o opengapps [(Aqui tem um artigo que eu segui pra fazer a instalação)](https://medium.com/@dai_shi/installing-google-play-services-on-an-android-studio-emulator-fffceb2c28a1)

**Comment by Ulisses1478** [comment]
> Pra ter acesso root vc precisa usar o emulador que não tem os aplicativos do google, vc instala eles dps com o opengapps [(Aqui tem um artigo que eu segui pra fazer a instalação)](https://medium.com/@dai_shi/installing-google-play-services-on-an-android-studio-emulator-fffceb2c28a1)

Recomendo o genymotion pra isso ele instala a isso sem o acesso root e faz automaticamente a parte do opengapps apertando um botão

**Comment by Iazzetta** [comment]
Alguem conseguiu usar o pynubank com conta PJ? To com um sistema pronto faltando apenas trocar de PF para PJ.

**Comment by andreroggeri** [comment]
@lazzetta me corrija se eu estiver errado, mas toda vez que você loga na conta PJ vc precisa fazer o processo biometrico (Enviar selfie) certo ? Teria que replicar isso dentro da lib (Que eu não sei se é viável)

Do resto os endpoints são os mesmos e funcionam em sua maioria.
