### ISSUE TITLE
Visualizar Operações de Saques em get_account_statements()

### ISSUE THREAD

**Issue by 3t1n** [andreroggeri/pynubank#140]
Ao receber as transações da minha conta corrente, não consegui obter os Saques efetuados em caixas 24 horas.
Creio que seja só adicionar esse parâmetro na consulta do GraphQL.

**Comment by andreroggeri** [comment]
Oi @3t1n você consultou as transações com o `get_account_statements` ? 

Se sim você pode olhar no `get_account_feed`, esse cara retorna todos os eventos da conta e por ele você consegue descobrir qual o parâmetro que vai na consulta GraphQL. Se não me engano é o campo `__typename`.

**Comment by 3t1n** [comment]
O issue foi resolvido, adicionando os '__typename', DebitWithdrawalFeeEvent e DebitWithdrawalEvent para a consulta do graphQL
