### ISSUE TITLE
Quanto tempo é possível ficar autenticado?

### ISSUE THREAD

**Issue by jeffersonmsb** [andreroggeri/pynubank#147]
Caso me autentique utilizando o QR Code, qual o limite até o Nubank desconectar a aplicação?

Queria deixar meus script atualizando minhas contas diariamente sem necessitar me autenticar todas as vezes.

Alguém já faz isso?

**Comment by andreroggeri** [comment]
Se não me engano são 7 dias. 
Acho que essa informação vem no response do login ou fica no próprio token (vc pode colar ele no site jwt.io pra ver) 

Para script automatizado o ideal é gerar o certificado.
Com ele vc autêntica manualmente só uma vez com o código que vem por e-mail.

**Comment by jeffersonmsb** [comment]
Me desculpe a ignorância, mas nunca vi de e-mail relacionado a essa API do Nubank. Onde é possível gerar o certificado?

**Comment by GGG-KILLER** [comment]
@jeffersonmsb no [exemplo de login por certificado](https://github.com/andreroggeri/pynubank/blob/master/examples/login-certificate.md) tem uma explicação de como gerá-lo:

> Após instalar a biblioteca, utilize o comando `pynubank` no terminal para iniciar o processo de geração de certificados.

**Comment by andreroggeri** [comment]
É isso aí mesmo, valeu @GGG-KILLER .

Dessa forma vc faz o mesmo caminho utilizado no Login pelo app. O código que você recebe por e-mail é esse aqui 
![Screenshot_20200816-211156_Gmail](https://user-images.githubusercontent.com/6232673/90347244-5f817780-e005-11ea-9e1d-599e69c454eb.jpg)

**Comment by jeffersonmsb** [comment]
Deu certo. Muito obrigado pessoal! Isso vai agilizar muito minhas contas pessoais.
