### ISSUE TITLE
Fazer o cache das requisições

### ISSUE THREAD

**Issue by andreroggeri** [andreroggeri/pynubank#15]
Por @janjitsu :

> Você tocou num ponto interessante @andreroggeri ...
> Na minha aplicação eu criei um cash das responses por que acabei ficando bloqueando também...
> E se fizessemos esse cache no pynubank?

> Claro que precisariamos ver uma forma mais inteligente de invalidá-lo. Mas pra mim faz sentido. Muita coisa não vai mudar e eu ainda não entendi muito bem qual a regra que bloqueia a máquina... Se soubessemos poderíamos antecipar o bloqueio na aplicação de alguma forma e evitá-lo.

**Comment by andreroggeri** [comment]
@janjitsu Eu cheguei a dar uma olhada nos headers pra ver se tinha alguma informação relevante, mas não achei nada... 😢 

Eu uso essa lib faz um bom tempo pra importar as minhas transações numa app de orçamento, e nunca tive problemas (Talvez seja pq seja uma chamada só que eu fazia por dia)

No seu caso, de puxar os lançamentos de cada fatura, com a data de abertura/fechamento de cada fatura, não seria o suficiente para evitar N chamadas ao `get_bill_details` ?

**Comment by andreroggeri** [comment]
Por exemplo:

A minha Fatura de Março: 
 - Abriu em 26/02/2018
 - Fechou em 29/03/2018

Se eu filtrar todas as transações entre esse período, eu já teria os lançamentos da fatura sem ter que fazer uma chamada ao `get_bill_details`

**Comment by janjitsu** [comment]
Sim, só que a minha idéia é conseguir separar todos os gastos por fatura, e o período da fatura não é conhecido, ou pode ter sido mudado ao longo do tempo. Eu mesmo mudei a data da fatura algumas vezes. Então apenas filtrando as transações eu conseguiria sim. Mas eu não tenho essa informação.

Mas voltando ao assunto do caching, realmente eu não fiz um uso real pra saber se a quantidade de requests seria suficiente sem precisarmos cachear nada. De qualquer forma, num ambiente de desenvolvimento, está sendo interessante pra mim fazer esse cache na aplicação. Para eu ficar testando e etc.

**Comment by janjitsu** [comment]
Faz muito sentido, talvez poderíamos fazer algum refactor das fixtures usadas no test para servirem aos dois propósitos!

**Comment by Lrcezimbra** [comment]
Eu estou usando a lib diariamente há alguns meses e até agora não tive nenhum tipo de bloqueio. Não vejo a necessidade de colocar um cache na lib, isso poderia ser mais facilmente controlado pela aplicação que utiliza a lib, fazendo poucas chamadas e guardando os dados em memória.

Quanto ao cache em desenvolvimento, não entendi essa parte. Nos testes as requisições já estão sendo mockadas. Qual o caso que seria util cachear? Como vocês fazem para testar? Eu normalmente uso o console do Chrome ou Postman para testar as requisições e funciona bem para mim.

**Comment by andreroggeri** [comment]
@Lrcezimbra durante o desenvolvimento o pessoal acaba executando o script muitas vezes e acaba bloqueando a conta (Eu fiquei 72hrs sem conseguir usar o site 😭, e o pessoal do suporte não faz o desbloqueio ). Sobre o cache eu tb estou pendendo para não implementar, mas achei interessante a solução do @janjitsu para usar o mock das respostas em tempo de desenvolvimento e depois troca para o cliente real.

**Comment by Lrcezimbra** [comment]
Entendi. Como eu uso TDD não tive esse problema, pois uso o requests mockado para testar.

Não sei se faz sentido alterar a lib para cachear as requisições, mesmo em desenvolvimento. Não consegui pensar numa forma simples de fazer isso. Talvez usar algo como Jupyter Notebook para testar durante o desenvolvimento sem fazer muitas requisições seja mais simples do que alterar a lib.

**Comment by andreroggeri** [comment]
Legal pessoal, acho que realmente isso não é um problema tão grande.
O cache realmente deve ser implementando no cliente pq são casos especificos, e pro desenvolvimento podemos usar o Jupyter para evitar ficar fazer a requisição toda hora (Ou fazer um mock simples da resposta que vc precisa).

Só adicionei um warning no readme para avisar sobre esse risco.

Obrigado pelas considerações @janjitsu @Lrcezimbra 👏
