### ISSUE TITLE
Problemas na autenticação por QR Code

### ISSUE THREAD

**Issue by fsmiamoto** [andreroggeri/pynubank#150]
Ao rodar um dos exemplos, modificado, não estou conseguindo o resultado esperado com a
autenticação por QR Code.

## Exemplo testado
```py
# nu.py
from pynubank import Nubank

nu = Nubank()
uuid, qr_code = nu.get_qr_code()

nu.authenticate_with_qr_code('cpf', 'senha', uuid)

print(nu.get_account_balance())
```
### Resultado
```
$ python nu.py
Traceback (most recent call last):
  File "nu.py", line 6, in <module>
    nu.authenticate_with_qr_code('cpf', 'senha', uuid)
  File "/home/shigueo/.local/lib/python3.8/site-packages/pynubank/nubank.py", line 82, in authenticate_with_qr_code
    response = self.client.post(self.discovery.get_app_url('lift'), json=payload)
  File "/home/shigueo/.local/lib/python3.8/site-packages/pynubank/utils/http.py", line 40, in post
    return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))
  File "/home/shigueo/.local/lib/python3.8/site-packages/pynubank/utils/http.py", line 32, in _handle_response
    raise NuRequestException(response)
pynubank.exception.NuRequestException: The request made failed with HTTP status code 404
```
- Python 3.8.5
- pynubank 2.4.0
### Esperado
Saldo na NuConta

Pelo visto houve alguma mudança no serviço `lift`.
Tentando fazer o request manualmente (com um token válido):
```
{
	"qr_code_id": "algum uuidv4",
	"type": "login-webapp"
}
```
retorna:
```json
# 404 Not Found
{
  "error": "Not Found"
}
```

Não sei se cometi algum erro ou talvez seja algo que não possamos fazer nada sobre, mas achei importante comentar por aqui.

Valeu!

**Comment by andreroggeri** [comment]
Exemplo completo em https://github.com/andreroggeri/pynubank/blob/master/examples/login-qrcode.md

**Comment by diegocostacmp** [comment]
Grato @andreroggeri funcionou com perfeicao, apos escanear o qrcode.

**Comment by fsmiamoto** [comment]
Obrigado @andreroggeri!
Um vacilo da minha parte mesmo.

**Comment by andreroggeri** [comment]
Acho que vale melhorar o exemplo do readme inicial =]

**Comment by fsmiamoto** [comment]
Ótima ideia, acho que posso ajudar nisso.
