### ISSUE TITLE
Problemas com função _save_auth_data no arquivo nubank.py

### ISSUE THREAD

**Issue by joaoser222** [andreroggeri/pynubank#166]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sergio/Documentos/pynubank/pynubank/nubank.py", line 99, in authenticate_with_cert
    self._save_auth_data(response)
  File "/home/sergio/Documentos/pynubank/pynubank/nubank.py", line 63, in _save_auth_data
    self.feed_url = auth_data['_links']['events']['href']
KeyError: 'events'

Este erro ocorre ao tentar autenticar. Precisei corrigir a função _save_auth_data do arquivo nubank.py substituindo os nomes de chaves que mudaram no request. A função corrigida fica assim:
def _save_auth_data(self, auth_data: dict) -> None:
        self.client.set_header('Authorization', f'Bearer {auth_data["access_token"]}')
        self.feed_url = auth_data['_links']['magnitude']['href']
        self.query_url = auth_data['_links']['ghostflame']['href']
        self.bills_url = auth_data['_links']['savings_account']['href']

**Comment by andreroggeri** [comment]
Você tá usando o certificado né ?

Aqui pra mim ainda funciona, talvez o Nubank esteja fazendo algum experimento ou rollout de uma feature nova, talvez seja necessário tentar um ou o outro.

Para o `bills_url` vc testou essa url de savings_account ? Não me parece correto

**Comment by andreroggeri** [comment]
Sim, mas vc chegou a chamar o método `get_bills` ? Pq eu acredito que vai dar erro

**Comment by teofilosalgado** [comment]
Também tive o mesmo problema :/ A solução foi alterar a função `_save_auth_data` como o @joaoser222 comentou mesmo.

**Comment by andreroggeri** [comment]
@teofilosalgado consegue fazer um PR com essa alteração ? Eu testo aqui se o `get_bills` funciona.

**Comment by teofilosalgado** [comment]
Consigo sim, em 5 minutinhos tá lá, vou só ligar o PC aqui!
