### ISSUE TITLE
Usar o GitHub Actions no lugar do Travis CI

### ISSUE THREAD

**Issue by thiagobrito** [andreroggeri/pynubank#167]
Quando estava fazendo meu PR eu percebi uma certa demora na execução dos builds do Travis CI. Não é nada assustador nem nada.

Mas buscando melhorar um pouco mais o projeto e deixar tudo integrado ao máximo em uma ferramenta só e aumentar a agilidade, já pensou em usar o GitHub Actions para fazer a integração contínua? O que acha?

**Comment by andreroggeri** [comment]
Hmm, eu vi aqui que o job mais lento levou 50 segundos... Com Actions seria mais rápido que isso ? :fearful:

**Comment by thiagobrito** [comment]
É, acho que não compensa mesmo não. A grande vantagem é estar tudo integrado em uma ferramenta apenas.
