### ISSUE TITLE
Como pegar a real fatura de pagamento?

### ISSUE THREAD

**Issue by thiagobrito** [andreroggeri/pynubank#173]
Uma das coisas que vem me incomodando no meu sistema e que as vezes ele não identifica corretamente em qual fatura será feito o pagamento da compra.

Por exemplo, todo dia 19 é a data de fechamento do meu cartão. Porém, em alguns casos, dependendo do horário e outros fatores que eu não consigo entender. A compra realizada pode ir para a fatura do mês atual, que está em fechamento, ou cair apenas no próximo mês.

Vocês conhecem algum campo ou alguma forma de fazer esta classificação da mesma forma que o Nubank para ficar mais assertivo?

**Comment by andreroggeri** [comment]
Se você recuperar as transações através da fatura não resolve o seu problema ?

**Comment by thiagobrito** [comment]
Ops, desculpe pela demora. Exatamente é isso mesmo, eu estava tentando pegar todas as contas a partir do nu.get_card_statements().

Apesar de fazer sentido na época na minha cabeça, agora ficou bem melhor do método que você disse. A desvantagem deste método é que não consigo enumerar as faturas futuras...

Mas para a minha situação é melhor fazer desta forma e perder esta funcionalidade no momento. Vou fazer um mix das duas no futuro.

**Comment by andreroggeri** [comment]
É, eu acho que o id da transação que retorna no `get_card_statements` é o mesmo id que retorna na fatura... Dá pra fazer esse mix e atualizar a data quando a fatura aparecer.
