### ISSUE TITLE
Transações recebidas e enviadas pelo PIX

### ISSUE THREAD

**Issue by maronezzi** [andreroggeri/pynubank#179]
Na lista das transaction, ainda não esta aparecendo quando é enviando ou recebido pelo PIX

![Seleção_070](https://user-images.githubusercontent.com/407525/100382851-f98c8f00-2ffa-11eb-8d84-bdd03221d61e.png)

**Comment by andreroggeri** [comment]
Se vc usar o método get_account_feed a transação aparece?

**Comment by maronezzi** [comment]
Aparece sim. Aparece como _'GenericFeedEvent'_

![Seleção_071](https://user-images.githubusercontent.com/407525/100515403-b21d1480-315a-11eb-8a6b-e848c07c6446.png)
