### ISSUE TITLE
Refresh token com autenticação via QRCode

### ISSUE THREAD

**Issue by emiliobristech** [andreroggeri/pynubank#182]
Pessoal, é possível atualizar o token se voce fez autenticação via QR Code?

Obrigado,

**Comment by andreroggeri** [comment]
Do que eu vi não @emiliobristech 
Pq no login só retorna o `access_token` e não retorna `refresh_token` (Em algum momentou retornou, mas eles removeram =/)

**Comment by emiliobristech** [comment]
Entendi @andreroggeri. Neste caso, como gerar o certificado? A documentação parte do pressuposto que o certificado já existe.

Muito obrigado,

**Comment by andreroggeri** [comment]
Na [seção de autenticação](https://github.com/andreroggeri/pynubank/blob/master/examples/login-certificate.md) tem explicado.

Mas talvez valha melhorar o formato para ficar mais claro.

Resumidamente basta executar no terminal o comando `pynubank` que vai rodar o [script que gera o certificado](https://github.com/andreroggeri/pynubank/blob/master/pynubank/utils/certificate_generator.py)

**Comment by emiliobristech** [comment]
Ah, entendi! Então o script gera o par, envia, recebe o código enviado via e-mail e gera o certificado fisico, digo, o arquivo. Agora está claro.

Muito obrigado!
