### ISSUE TITLE
Operações de Transferencia, DOC e TED

### ISSUE THREAD

**Issue by emiliobristech** [andreroggeri/pynubank#183]
Pessoal, qual o motivo das operações de Transferencia, DOC e TED não estarem disponiveis na API? É alguma restrição do Nubank ou teoricamente é possível?

Obrigado,

**Comment by andreroggeri** [comment]
Pq quando geramos o certificado, fazemos só o primeiro passo da autenticação, pra fazer operações de escrita (transações, pagamentos, etc) teria que fazer o processo de mandar a foto. 

Nunca consegui fazer esse segundo passo via api.

**Comment by SamukaDEV** [comment]
@andreroggeri , entao agora é tecnicamente possivel fazer esse tipo de operação? ja que discutimos e conseguimos pegar a autenticação do certificado depois de autenticado por foto no aplicativo?
como foi debatido na issue #419 ?

**Comment by andreroggeri** [comment]
Em teoria sim, teria que inspecionar as requisições que o app faz e implementar aqui.
