### ISSUE TITLE
Necessidades PIX

### ISSUE THREAD

**Issue by uxmarinho** [andreroggeri/pynubank#184]
Excelentíssimos, sou novo aqui nessa busca pelas apis loucas do nubank, eu tenho a necessidade hoje de gerar qr code de pagamento PIX, eu dei uma pesquisada com Insomnia nas rotas "discovery" e consegui Bearer token, mas ainda está muito confuso como prosseguir nessa empreitada, alguém pode me apontar caminho para melhorar minha vida  na busca dessas rotas, geração de certificado etc... ou se possível quem tiver interessado podemos fazer uma call ou grupo do discord para montarmos uma documentação e ficarmos no mesmo nível, evoluímos mais rápido trabalhando juntos!!! Tmj, Muitíssimo Grato.

OBS: Tanto Astrocoders/nubank-api quanto pynubank são api para consultar apis, acho que seria mais produtivo, focarmos na utilização das apis do nubank em si e deixar backend a cargo do desenvolvedor.... só uma opinião para quem tiver interessado.

**Comment by andreroggeri** [comment]
Fala @uxmarinho .

Realmente adicionar novas funcionalidades não tem sido fácil pra ninguém.

Me passaram esse caminho do Insomnia mas ainda não parei para ver o quão fácil/dificil é implementar uma feature com o que ele gera.

Eu fiz essa lib em cima das requests que o app envia, cheguei a detalhar um pouquinho na issue #139  como que eu faço pra extrair isso do app. Veja se isso te ajuda, se não podemos trocar uma idéia pra criarmos uma doc mais completa.

**Comment by uxmarinho** [comment]
Criei um grupo no discord, podemos documentar evoluções por lá, e qualquer interessado pode contribuir juntamente... Eu estou justamente vendo a #139 aqui kkk, não é meu perfil redes, mas vou buscar identificar essas rotas, antes gostaria de fazer o que o pybank já faz de gerar certificado e Bearer token e acessar informações básicas, para depois buscar rotas de geração de recebíveis com o PIX. Vamos que vamos ....

| Discovery NuBank Api
https://discord.gg/xsffzHMm

**Comment by andreroggeri** [comment]
Que tal um gitter ? Podemos deixar o conhecimento público e colocar um badge no README

**Comment by uxmarinho** [comment]
Nunca utilizei, mas entendo a proposta, poderia criar a comunidade lá?

**Comment by andreroggeri** [comment]
Isso, criei lá => https://gitter.im/pynubank/community#

Vou adicionar uma badge no repo tb
