### ISSUE TITLE
Ajuste de query para filtrar extrato por data.

### ISSUE THREAD

**Issue by PedroHLeal** [andreroggeri/pynubank#186]
Olá, 

Estou tentando customizar a query de recuperação de extrato de conta para fazer uma filtragem por data:

{
    viewer {
        savingsAccount {
            id
            feed (where: {postDate: {gt: '$startdate'}}) { <--
            .....
}

Mas sem sucesso, a requisição me traz falha no parsing da query. Pesquisando um pouco mais sobre GraphQL percebi que esse filtro pode variar entre ORMs GraphQL. Como eu poderia fazer isso para o Nubank? Qual a ORM eles utilizam?

**Comment by andreroggeri** [comment]
Oi Pedro.

Eu fiz alguns testes e não consegui fazer esse filtro que vc tá tentando.
No máximo consegui limitar a quantidade de registros.

Inclusive no próprio app eu não encontrei nenhum lugar que faça essa paginação, sempre trás tudo =/

**Comment by PedroHLeal** [comment]
Pois é, eu reparei também que o aplicativo trazia todos os registros depois que fiz a pergunta.
Como você conseguiu limitar os registros? Creio que pode ser útil para nossos registros!

Muito obrigado pela atenção!

**Comment by emiliobristech** [comment]
> Oi Pedro.
> 
> Eu fiz alguns testes e não consegui fazer esse filtro que vc tá tentando.
> No máximo consegui limitar a quantidade de registros.
> 
> Inclusive no próprio app eu não encontrei nenhum lugar que faça essa paginação, sempre trás tudo =/

Oi André, esse limite de registros é feito no GraphQL? Fiquei curioso sobre como vc conseguiu fazer...

**Comment by andreroggeri** [comment]
@PedroHLeal perdão pela demora acabei esquecendo de responder, vou mandar um gql de exemplo com limite.

Isso aí Emilio.

A doc trás isso: 
![image](https://user-images.githubusercontent.com/6232673/102287890-21945180-3f1a-11eb-8fb0-971434872880.png)

Então um exemplo de query limitando os registros (Fica fixo na query) é assim:

```
{
  viewer {
    savingsAccount {
      feed(limit: 10) {
        id
        title
        detail
      }
    }
  }
}

```

**Comment by emiliobristech** [comment]
Show @andreroggeri! Muito obrigado!
