### ISSUE TITLE
Não consigo inicar o processo de geração do certificado

### ISSUE THREAD

**Issue by jucaalves** [andreroggeri/pynubank#193]
Após instalar a biblioteca, o comando pynubank não é reconhecido no bash (estou usando windows com o git bash no vscode).

Está faltando alguma etapa?

**Comment by teofilosalgado** [comment]
Olá!
Teria como você verificar pra mim se o caminho `C:\Users\[seu usuário]\AppData\Local\Programs\Python\Python39\Scripts` está no seu Path? Outra coisa, dá uma olhada se nesse caminho existe um `pynubank.exe` como na imagem abaixo:
![image](https://user-images.githubusercontent.com/7178504/102833721-a5de4d00-43d0-11eb-8fe1-93b76ccb17c5.png)

**Comment by andreroggeri** [comment]
É isso aí, provavelmente a pasta Scripts do python não está no seu path.

O caminho que o @teofilosalgado passou é uma boa, e se vc não conseguir mesmo assim, pode criar um script que chama o gerador de certificado:

```
from pynubank.cli import main

main()
```

Isso deve ser o suficiente.
