### ISSUE TITLE
Revoke authorization token

### ISSUE THREAD

**Issue by JpOttaviano** [andreroggeri/pynubank#197]
Hi, I have been using this repository as a guide to map requests to Nubank and i have noticed that the sessions remain open, at least for more than a day. I tried sending query post requests with an authorization token generated the day before and it still sends a 200 ok response back.

 Is there any request to close the opened sessions from the server?

**Comment by andreroggeri** [comment]
Hi @JpOttaviano I checked the login response and it returns a URL to revoke the token, I'll create a quick PR for this
