### ISSUE TITLE
O que é o client_secret e por que é fixo?

### ISSUE THREAD

**Issue by Sroccchi** [andreroggeri/pynubank#20]
Estou usando a API e funciona perfeitamente, pretendo alterá-la para ter um controle explícito da frequência de requests, repasso as alterações se eu achar que deu certo.

De volta ao não-problema o que é esse "client_secret"? Parece um hash, mas é fixo. Imaginei que isso fosse causar erro ao tentar logar, mas fiz o login normalmente, tudo funciona. 

A mesma pergunta é válida para "client_id" = "other.conta"

**Comment by andreroggeri** [comment]
Essas informações eram usadas no login pelo site.
Acabei de olhar novamente, e o login mudou, até a URL está diferente.

Sobre o controle de frequência de requests, acho interessante, inclusive já mandei email pro meajuda@nubank.com.br pra ver se eles ajudam com essas informações, mas ainda não tive retorno.

**Comment by Sroccchi** [comment]
Eu alterei arbitrariamente o valor das duas variaveis e ainda consegui logar normalmente, mas quando eu apaguei as duas, recebi <400> Bad request. O que quer que seja é com o Nubank... Vou fechar a discussão, mas se tiver algo a adicionar volta aqui depois. Valeu!

**Comment by Sroccchi** [comment]
Testei a seguinte configuração e funcionou normalmente
"client_id": "oxthar.contxa",
"client_secret": "balululaueIa-lrjfsNEFaslf"

Considerando que uma alteração arbitrária não gerou erro ao logar, talvez fosse bom randomizar essas variaveis. No mínimo client_secret, que parece um hash. Deve haver alguma boa razão pra não mantê-la igual.

**Comment by andreroggeri** [comment]
Quando eu escrevi essa lib, me baseei na versão em JS (
https://github.com/Astrocoders/NUBANK-API).

Que por usa vez pegaram essas informações no próprio formulário de login
(que hoje funciona diferente) e pelo o que eu me lembre essa informação era
sempre igual.


Em Sáb, 12 de mai de 2018 16:00, Sroccchi <notifications@github.com>
escreveu:
