### ISSUE TITLE
Is is possible to get Credit Card info?

### ISSUE THREAD

**Issue by JpOttaviano** [andreroggeri/pynubank#207]
I noticed that while it is possible to get credit card feed transactions, there is no information returned of the credit card details (brand, card number).
Is there another endpoint available for that or is there no access to that information?

**Comment by andreroggeri** [comment]
I think that the credit card number is a confidential data that shouldn't
be returned anywhere (but if you find somewhere in the app it may be
possible to replicate here).

The card brand is always mastercard isn't?

Em ter, 26 de jan de 2021 10:53, Juan Pablo Ottaviano <
notifications@github.com> escreveu:

**Comment by JpOttaviano** [comment]
Yes the card brand Nubank issues is Mastercard only. The card details (number, expire date, etc) are available in the app.

**Comment by andreroggeri** [comment]
Where? I can only find this information in the virtual card menu (but that
isn't for the physical card)

Em ter, 26 de jan de 2021 20:59, Juan Pablo Ottaviano <
notifications@github.com> escreveu:

**Comment by JpOttaviano** [comment]
Nevermin, you were correct. No physical card info. I thougth you migthve crossed into something like that while analyzing the endpoints but I guess not.
Nevertheless I will try to see if anything comes up crawling the endpoints.

Many thanks anyway!
