### ISSUE TITLE
Autenticação GET

### ISSUE THREAD

**Issue by horanerd** [andreroggeri/pynubank#212]
Cara estou tentando portar isso para php, me tira uma dúvida como eu faço a autenticação via curl estou fazendo uns testes, mas ainda nada certo consegue me dar uma luz.

Qual as keys e qual a url que coloco só pra fazer o login ? 

consegui fazer um get em https://prod-s0-webapp-proxy.nubank.com.br/api/discovery
Só que ai me retorna isto aqui:

{
    "register_prospect_savings_web": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LBijYSQBQwHMScYOrw1dfGdoonaFA.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVyL3NhdmluZ3Mtd2Vi",
    "register_prospect_savings_mgm": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LDN6gRSzstj8Zs1nYYayRriWutMYg.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVyL3NhdmluZ3MtbWdt",
    "pusher_auth_channel": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LAeA3V5-G9OzDz-GUxxb4QaTZpr4g.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jaGF0LWNsaWVudC5udWJhbmsuY29tLmJyL2FwaS9wdXNoZXIvYXV0aA",
    "register_prospect_debit": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LCYbtgnjPgX7MHBwJG2pPTWwZmkVQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVyL2RlYml0",
    "reset_password": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LAlsb_71MAcRvpX9jCh1FaKvBEuVg.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL3Jlc2V0LXBhc3N3b3JkL2NvbXBsZXRl",
    "register_prospect": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LBmwSyeH60uJKrevw-E9FDjqxayww.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVy",
    "register_prospect_savings_request_money": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LCmAsPA_3bO08u7hNM8U0w6zz-hdQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVyL3NhdmluZ3MtcmVxdWVzdC1tb25leQ",
    "register_prospect_global_web": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LCO3gflk3zixYHuNpceiQBJnsYTCQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL3Byb3NwZWN0L3JlZ2lzdGVyL2dsb2JhbC13ZWI",
    "register_prospect_c": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LD1RQ-IG6wyp1A5C4Qrvtidi3xxaw.aHR0cHM6Ly9wcm9kLWdsb2JhbC1iaXJkLWJveC5udWJhbmsuY29tLmJyL2FwaS9jb21wYW55LXByb3NwZWN0cw",
    "request_password_reset": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LClV6czXGMzwOAShSFHH32BBNcZrg.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL3Jlc2V0LXBhc3N3b3Jk",
    "auth_gen_certificates": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LApUVAX0b5R5DnjMw3-9ibnk8UnZg.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL2dlbi1jZXJ0aWZpY2F0ZXM",
    "login": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LBUC2Tx4PB-W6VD1SEIOd2xp14EDQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL3Rva2Vu",
    "email_verify": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LDlmi5eGa7ikt-NlESQWn3Y4MoSTA.aHR0cHM6Ly9wcm9kLWdsb2JhbC1jdXN0b21zLm51YmFuay5jb20uYnIvYXBpL2VtYWlsL3ZlcmlmeQ",
    "auth_device_resend_code": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LDYdvoPz_8E2Hn5QE5zBfzyVPPaEQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL2RldmljZS9hdXRob3JpemUtcmVzZW5kLWNvZGU",
    "msat": "https://prod-global-webapp-proxy.nubank.com.br/api/proxy/AJxL5LA68SUWvd84x5gAXPeCJlaVpNJ4Mw.aHR0cHM6Ly9wcm9kLWdsb2JhbC1taWNhLm51YmFuay5jb20uYnIvYXBpL21zYXQ"
}

Ainda não entendi como ele se comunica com a api para conseguir acessar a conta.

**Comment by andreroggeri** [comment]
Pra autenticar pelo fluxo de QRCode vc usa a chave `login`.

Vc faz um POST nessa url com esse conteúdo: 
```
{
    "grant_type": "password",
    "login": "SEU CPF",
    "password": "SUA SENHA",
    "client_id": "other.conta",
    "client_secret": "yQPeLzoHuJzlMMSAjC-LgNUJdUecx8XO"
}
```

**Comment by andreroggeri** [comment]
Obs: Pode chamar lá no [gitter](https://gitter.im/pynubank/pynubank?) que talvez seja mais fácil te ajudar num formato de chat :smiley:
