### ISSUE TITLE
Transferências utilizando Pix

### ISSUE THREAD

**Issue by jeffersonmsb** [andreroggeri/pynubank#213]
Olá, as transferências por Pix estão vindo dessa maneira, caso possa interessar a alguém.
Elas não aparece porque estão filtradas na biblioteca. Acredito que no futuro eles mudem isso.

'__typename': 'GenericFeedEvent'

**Comment by andreroggeri** [comment]
Pois é, e o pior é que não tem como pegar o valor direto, tem que extrair da mensagem =/

**Comment by jeffersonmsb** [comment]
É... Tou refatorando meu programa de finanças pessoais e percebi isso.
