### ISSUE TITLE
Autenticação com refresh token

### ISSUE THREAD

**Issue by Ulisses1478** [andreroggeri/pynubank#215]
Quanto tempo o refresh token fica válido para acessar a api do nubank?

Pois percebi que depois de certo tempo a autenticação com o mesmo retorna status code 403

```
pynubank.exception.NuRequestException: The request made failed with HTTP status code 403
```

No caso do aplicativo do nubank como ele mantém o token ativo ele salva as credenciais no client?

**Comment by andreroggeri** [comment]
Se não me engano o token é valido por 7 dias, mas vc pode confirmar abrindo ele no https://jwt.io

Acho que é o campo `exp`.

Todo login com refresh token retorna um novo refresh token, que tem a expiração renovada

**Comment by Ulisses1478** [comment]
Ah sim, excelente
