### ISSUE TITLE
Lançamentos da NuConta faltando

### ISSUE THREAD

**Issue by lpsouza** [andreroggeri/pynubank#217]
Olá!

Reparei que alguns lançamentos da NuConta não estão aparecendo quando mando obter usando `nu.get_account_statements()`.

O que posso comentar, são lançamentos de Janeiro de 2021 pra fente, e somente o que eu transferi ou paguei. O que eu recebo esta sendo recebido corretamente, o que acaba causando uma inconsistência nos valores informados pelo `pynubank` e o app do nosso roxinho!

O que será que pode estar acontecendo? Alguém já verificou um erro assim?

**Comment by andreroggeri** [comment]
Isso tem um pouco a ver com a #213 pq as transferências Pix por exemplo não retornam o valor no campo `amount`.

Pra pegar todos os eventos da sua conta vc pode chamar o `nu.get_account_feed()` e para esses casos que o valor vem no campo `detail` precisaria extrair o valor da string manualmente =/

**Comment by lpsouza** [comment]
Legal @andreroggeri! Não tinha visto essa função na documentação... Achei interessante que ela traz tb o que foi movimentado no cofrinho do Nubank tb... Valeu a dica, já estou refatorando aqui o meu código usando essa function!
