### ISSUE TITLE
Rendimentos do NuConta

### ISSUE THREAD

**Issue by lpsouza** [andreroggeri/pynubank#218]
Reparei que quando uso a função `nu.get_account_feed()` e faço uma soma das entradas e faço a diferença com a soma das saídas tem uma diferença que acredito ser os dividendos dos rendimentos do NuConta. Existe como obter esse tipo de informação para fechar o valor do saldo? Tentei com o `nu.get_account_investments_details()`, mas não consegui obter (ou não entendi como obter o rendimento 😅).

**Comment by Ulisses1478** [comment]
Quando você puxa o ```nu.get_account_investments_details()``` vai ter retornar um array nesse array for faz um loop e pega todos os 'redeemedBalance' no redeemedBalance o yield é o lucro dos investimentos

**Comment by lpsouza** [comment]
Olá @Ulisses1478, infelizmente este campo não bate nem de perto os valore incorretos quando fazemos a diferença de todos as entradas e de todas as saídas, mas valeu o apoio!

**Comment by Ulisses1478** [comment]
Como eu disse ele não pega o histórico dos investimentos. É possível que eu faça isso em um futuro próximo e dê um pull request no repositório

**Comment by jeffersonmsb** [comment]
Eu uso um bot do telegram pra gerenciar minhas finanças. Daí tive que fazer uma rotina que verifica essas pequenas diferenças e pergunta se quero ajustar como rendimento do nubank. É o que tem pra hj rsrs.

**Comment by jeffersonmsb** [comment]
Obrigado @Ulisses1478 arranjei um tempinho pra implementar hj.

**Comment by lrezende** [comment]
Eu não sei se deveria estar comentando nessa issue fechada, mas vamos lá...

Eu sou chato, fecho o saldo diariamente... Então eu mando email pra lá e peço um extrato de rendimentos. Vem um email com dois arquivos, um pdf e um csv com a mesma informação.

> "Data","Entradas","Saídas","IR","IOF","Rendimentos","Saldo Líquido"
> 2021-10-25,0.00,0.00,0.00,0.00,0.00,8018.20
> 2021-10-26,0.00,0.00,0.00,0.00,1.90,8018.54
> 2021-10-27,0.00,3190.85,0.14,2.41,1.90,4828.11
> 2021-10-28,0.00,0.00,0.00,0.00,1.14,4828.47

Ou seja, eles têm o saldo dia a dia. Mas não tem no aplicativo e não sei se é possível pegar via api.

Eu pego esse csv e vou verificando se o saldo diário bate. Se não base eu verifico as entrada e saídas. Se elas batem, eu lanço a diferença entre o saldo deles e o meu.
