### ISSUE TITLE
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:777)

### ISSUE THREAD

**Issue by andreroggeri** [andreroggeri/pynubank#22]
A URL que gera o token está com problema de certificado: https://prod-auth.nubank.com.br/api/token

**Comment by jeffersantoss** [comment]
Agora precisa de um proxy...
https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/AJxL5L2Tx4PB-W6VD1S2xp14EDQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL3Rva2Vu

Cada rota aponta para o endereço de um proxy https://prod-s0-webapp-proxy.nubank.com.br, seguido de um URI. No caso de login, por exemplo, o endereço completo fica https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/AJxL5L2Tx4PB-W6VD1S2xp14EDQ.aHR0cHM6Ly9wcm9kLWdsb2JhbC1hdXRoLm51YmFuay5jb20uYnIvYXBpL3Rva2Vu.

A primeira parte (antes do .) é um prefixo para o proxy vigente, e a segunda, é um endereço codado em base64: https://prod-global-auth.nubank.com.br/api/token.

**Comment by andreroggeri** [comment]
Nossa, já salvou um tempo de investigação.
Uma dúvida, a primeira parte então é sempre a mesma ?


Consegue mandar um PR ?

**Comment by jeffersantoss** [comment]
Cada rota aponta para um endereço de proxy diferente... acredito que deva sim ser a mesma...
Dá uma olhada nessa requisição: https://prod-s0-webapp-proxy.nubank.com.br/api/discovery
![image](https://user-images.githubusercontent.com/10839497/42140148-0ca8089c-7d71-11e8-9669-0b7e5ece5ca1.png)

**Comment by marcelma** [comment]
Olá @andreroggeri , Fiz um PR utilizando a URL que o @jeffersantoss informou. Estou começando no Python 😄 . Comentários são muito bem vindos.

**Comment by andreroggeri** [comment]
Pessoal, muito obrigado pela colaboração ! ❤️
