### ISSUE TITLE
Topic: Ratelimit

### ISSUE THREAD

**Issue by ceelsoin** [andreroggeri/pynubank#238]
Abri essa issue não para reportar bug, mas para entender e discutir sobre ratelimit e possibilidades de contornar isso uma vez que somos um wrapper na api não pública.

Estou fazendo a leitura do feed para posteriormente coletar dados de comprovantes dessas transações (especificamente transfer_in de pix), não cheguei em meus testes ser bloqueado, mas temo isso em ambiente de produção.

A dificuldade no meu caso é ter que enviar a query de comprovantes que o @Ulisses1478 apresentou na issue #226 a cada transação do meu feed (claro eu não preciso repetir as transações que li antes) mas em um alto volume isso pode ficar complicado novamente.

Se eu disparo a cada 4 ou 5 minutos uma leitura no feed, com a possibilidade de ler o feed e o comprovante em uma única query acredito reduzir bastante meu hit na api, mas caso isso não seja possível eu precisarei fazer diversas leituras na api por minuto, então gostaria de saber quais pontos já foram considerados sobre ratelimit nesta api

**Comment by andreroggeri** [comment]
Fala @ceelsoin 

Até agora eu não tive nenhum problema com excesso de chamadas. 
O ponto onde o Nubank parece ser mais cauteloso é na autenticação, quando tentei fazer vários logins fiquei sem acesso a minha conta por um tempo (O app se manteve logado).


Não sei se alguém usou a API de maneira intensiva pra trazer mais informações aqui

**Comment by Ulisses1478** [comment]
Eu usei a api de maneira intensiva durante meses, eu tentei utilizar atualização a cada 5 minutos que fazem 3 requests não foi muito bem acabou dando too many requests mas coloquei 21 minutos para testar e roda até hoje talvez conseguisse 11 min mas não quis arriscar ainda

**Comment by ceelsoin** [comment]
Eu desenvolvi uma forma de autenticar transações pix na conta deles, estava pensando em verificar a cada 5 minutos, agora vou tentar fazer a cara 11 e vejo se vou conseguir bons resultados com esse time. A informação que deram vai ser muito importante, obrigado.

**Comment by Ulisses1478** [comment]
Se puder avisar se os 11min funciona tranquilo agradeco

**Comment by Ulisses1478** [comment]
Eu consegui abaixar pra 10 minutos a verificação sem problemas rodando a uns meses já ele faz 3 requests a cada 10 min na api do nubank.

**Comment by isomiluizdasilva** [comment]
Louco por essa função "LER feed e o comprovante" usando a API em PHP. Acho que vou ter de me dedicar a prender Phyton :)

**Comment by Bezouro** [comment]
> Louco por essa função "LER feed e o comprovante" usando a API em PHP. Acho que vou ter de me dedicar a prender Phyton :)

Eu fiz uma versão em js xD
Mas ai galera, eu faço essa verificação a cada 20 segundos ha mais de 1 ano e nunca tive sequer um problema de too many requests em produção, então digo: confia...
pra garantir que tudo vai correr bem, eu tava puxando na query feed acho que os 100 ultimos items, filtrava tudo que era transfer_in e depois checava quais desses eram pix, salvava tudo em cache e depois só analisava o que não tava no cache
