### ISSUE TITLE
Exportar registros como OFX

### ISSUE THREAD

**Issue by alanjds** [andreroggeri/pynubank#24]
Vários aplicativos importam contas via OFX. Ter uma maneira de coletar OFX de sua Nuconta ou cartão facilitaria muito o controle de gastos via aplicativos.

**Comment by andreroggeri** [comment]
@alanjds legal a sua idéia, inclusive foi justamente por isso que eu criei essa lib.


Não sei qual o esforço disso,  se for algo simples poderiamos fazer aqui mesmo, mas se for aumentar muito a complexidade talvez faça sentido criar um repo a parte e usar o `pynubank` como dependência.

PRs são bem-vindos  ! 😄

**Comment by andreroggeri** [comment]
Vou fechar essa issue por falta de atividade.

PRs continuam sendo bem-vidas ! 👍

**Comment by andreroggeri** [comment]
Fala @alanjds concordo com a abordagem de deixar issues de melhoria abertas.

Porém levantei o ponto sobre isso fazer sentido aqui no pynubank ou em uma lib a parte, e não houve nenhum retorno de ninguém.

Continuo aberto para discutir esse ponto ! 👍
