### ISSUE TITLE
Autorização de dispositivo necessária após geração do certificado

### ISSUE THREAD

**Issue by vanessa** [andreroggeri/pynubank#246]
Segui os passos indicados em https://github.com/andreroggeri/pynubank/blob/master/examples/login-certificate.md para gerar o certificado, e consegui salvá-lo, mas logo após o processo, recebo esse e-mail do Nubank, pedindo para ir no "aplicativo" do pynubank e autorizá-lo como dispositivo (e acredito que por causa disso todas as requisições retornam 400).

![LNPtRvLn](https://user-images.githubusercontent.com/23136832/124025502-e265b380-d9c6-11eb-86f0-7c1f3c1918d5.png)

Tem alguma medida que preciso modificar na minha conta para permitir o acesso ou algum passo que deixei de fazer?

**Comment by vanessa** [comment]
Pode ignorar essa issue, eram as variáveis de ambiente que não estavam setadas corretamente.

**Comment by SkyLeite** [comment]
Estou com esse problema também. Existe uma solução na documentação?

**Comment by andreroggeri** [comment]
Isso não é um problema, o certificado gerado não tem permissão pra fazer transações, pagar boleto, pix, etc. É isso que o email está dizendo.

Se você não está conseguindo usar a lib, abre uma issue com o código que você está utilizando por favor

**Comment by SkyLeite** [comment]
Entendi. Acho que seria útil adicionar essa informação nos docs. Amanhã abro uma PR :)

Obrigada
