### ISSUE TITLE
Será que é fraude????

### ISSUE THREAD

**Issue by eritonfarias** [andreroggeri/pynubank#249]
Curiosamente e coincidentemente logo após testar esse projeto meu cartão recebeu diversas compras falsas (4 compras falsas).

Por segurança já fiz o pip uninstall

Adeus

**Comment by andreroggeri** [comment]
Não é possível que o pynubank faça qualquer tipo de operação na sua conta (transferência, pagar boleto, gerar cartão virtual) pois não fazemos o segundo passo de verificação (que é enviar uma selfie segurando um documento). 

Além disso se você quiser confirmar, provavelmente as compras fraudulentas foram feitas no seu cartão físico, que não é possível obter os dados (número e cvv) pela api (não existe essa info no App). 

De qualquer forma o código é aberto e pode ser inspecionado para qualquer tipo de "fraude"

**Comment by jeffersonmsb** [comment]
Apenas queria adicionar que uso faz anos para minhas finanças pessoais, nunca tive nenhum problema. De qualquer maneira, não precisa acreditar em ninguém, o código é aberto.
