### ISSUE TITLE
Checagem de pagamentos via pix

### ISSUE THREAD

**Issue by gslima** [andreroggeri/pynubank#267]
Existe alguma funcionalidade da API para checagem se pagamentos via PIX foram efetivados?

**Comment by andreroggeri** [comment]
Ainda não. Tem algo começado na #260, através daquele novo método será possível obter o identificador do qrcode.

Mas pra isso será necessário fazer uma chamada pra cada transação da lista.

Fora isso não tem, se eles implementarem no app podemos replicar aqui.

Relacionado: #258

**Comment by gslima** [comment]
Gostaria de colaborar com o projeto, contudo, sou relativamente iniciante. Minha ideia é contribuir com a implementação do sistema com o pix. Como faço para não usar o app com uma conta real e ainda assim obter o status de um pix? Há alguma documentação neste sentido? (eu entendi que tem dados em mocked_responses, via teste com MockHttpClient(), porém não vi resposta mock para o método get_pix_status).

**Comment by andreroggeri** [comment]
Eu fui gerar os mocks e acabei me empolgando pra finalizar a implementação

Na versão 2.14.0 já é possível gerar o QRCode com identificador e recupera-lo de uma transação.

Exemplo adicionado na [documentação](https://github.com/andreroggeri/pynubank/blob/master/examples/pix.md#obtendo-o-identificador-de-uma-transa%C3%A7%C3%A3o)
