### ISSUE TITLE
Requisitando pagamento via PIX

### ISSUE THREAD

**Issue by mrdamaia** [andreroggeri/pynubank#276]
Olá boa tarde,

Já consegui gerar o meu certificado e verificar o saldo da conta. Mas quando tento usar o exemplo de pix, o primeiro print :

print(data['keys']) # Retorna lista de chaves cadastradas no Pix

retorna:

[{'id': 'zzzzzzzzzzzzzz', 'kind': 'CPF', 'value': '12345678912', 'formattedValue': '123.456.789-10', 'itemDeepLink': 'nuapp://pix/dict/key-details/zzzzzzzzzzzzzz', 'badge': None}, {'id': 'yyyyyyyyyyyyyyyyyyyyyyy', 'kind': 'EMAIL', 'value': 'john@doe', 'formattedValue': 'john@doe', 'itemDeepLink': 'nuapp://pix/dict/key-details/yyyyyyyyyyyyyyyyyyyyyyy', 'badge': None}]
xxxxxxxxxxxxxxxxxxxxxxxx

estou fazendo algo de errado?

Desde já agradeço!

**Comment by andreroggeri** [comment]
Você está utilizando o `MockHttpClient` como no exemplo abaixo ?

```
nu = Nubank(MockHttpClient())
```

Se sim vc não está chamando o Nubank de verdade, e sim um dublê. (É bem útil para testes).
Basta remover o `MockHttpClient()` do código

**Comment by mrdamaia** [comment]
Perdão pelo vacilo mestre. Agora funcionou certinho. Muito obrigado!
