### ISSUE TITLE
Inscrever nas notificações

### ISSUE THREAD

**Issue by andreroggeri** [andreroggeri/pynubank#283]
Assim como o app consegue receber as notificações quando algo acontece na conta, poderíamos fazer algo parecido aqui.

Cheguei a ver alguns requests que retorna o token do Firebase, com ele seria possível se inscrever nos tópicos e receber as notificações.

único problema é que não encontrei nenhuma implementação em python do firebase que consiga escutar as notificações, apenas enviar

**Comment by Ulisses1478** [comment]
Seria muito top se inscrever nas notificações do firebase acho que se não tiver nada pra fazer isso dê pra fazer na mão grande, consegue me enviar os dados que você conseguiu pegar via e-mail?

**Comment by diegomdrs** [comment]
Estava pesquisando justamente sobre isso. Tenho uma aplicação usando Google Apps Script e outra em node.js (https://github.com/diegomdrs/nubank-token-api) para obter e atualizar o token para autenticar na API do Nubank e gostaria muito de conseguir obter trigger qualquer para executar a consulta do extrato do meu cartão.

A princípio pensei que quando abrissemos a versão web do Nubank houvesse um Websocket com as atualizações das compras do cartão, mas não há. A gente tem que dar F5 mesmo pra atualizar a versão web :). Em seguida cheguei ao FCM e não tenho a mínima ideia de como monitorá-lo no Android para obter as mensagens recebidas e o token
