### ISSUE TITLE
Data e hora nas transações da Nuconta

### ISSUE THREAD

**Issue by jeffersonmsb** [andreroggeri/pynubank#284]
Alguém entende o porquê a data e hora não estão disponíveis no endpoint que retorna as transações da nuconta?

**Comment by jeffersonmsb** [comment]
Acredito que a resposta está na #258

**Comment by andreroggeri** [comment]
É isso aí...

Pra montar a tela de detalhes o app faz uma nova request.
Deve ser possível fazer isso, mas na prática vai acabar sendo inviável pq se enviar um monte de requisição é bem provavel de que a conta seja bloqueada
