### ISSUE TITLE
Api de empréstimos

### ISSUE THREAD

**Issue by Ulisses1478** [andreroggeri/pynubank#286]
Agora com a parte de empréstimos seria interessante incluir essa parte da api aqui no repositório eu posso ajudar a pegar os requests caso alguém esteja disponível no momento pra fazer.

**Comment by andreroggeri** [comment]
Será que isso vai rolar ?

Atualmente não conseguimos fazer nada que faça alguma alteração na conta (Transferencia, gerar cartão virtual, etc) pq não fazemos a segunda parte da autenticação que é enviar a foto com o documento

**Comment by Ulisses1478** [comment]
Vai sim, não precisa colocar aquela autênticação com a senha pra ver os empréstimos, agora fazer é outra história.
