### ISSUE TITLE
Faceboook pay (Whatsapp)

### ISSUE THREAD

**Issue by mherszenhaut** [andreroggeri/pynubank#289]
Impressão minha ou esse método de pagamento não tá aparecendo no feed?

**Comment by andreroggeri** [comment]
Vc chegou a ver se a transação aparece com o método `get_account_feed` ?

**Comment by Bezouro** [comment]
Tem algumas transações que não aparecem no feed mesmo, 
@andreroggeri Essa query aqui mostra tudo do feed, da uma conferida
`
{
            viewer {
                savingsAccount {
                    feedItems(cursor: ${cursor}) {
                        pageInfo {
                            hasNextPage
                        }
                        edges {
                            cursor
                            node {
                                id
                                title
                                detail
                                postDate
                                displayDate
                                footer
                                iconKey
                                detailsDeeplink
                                tags
                                kind
                            }
                        }
                    }
                }
            }
        }
`

**Comment by vctrd** [comment]
Obrigado pela query @Bezouro , acredito que ainda tem itens que não estão presentes, como por exemplo o cashback resgatado dos pontos do cartão que aparecem no aplicativo mas não com essa query

**Comment by andreroggeri** [comment]
@vctrd vi aqui que mudando o correlation-id passou a trazer mais informações.

Já já vou lançar uma nova versão que trás o feed paginado e deve trazer todas as transações, se você pude testar =]

**Comment by vctrd** [comment]
obrigado, desculpa a demora, mas estamos com todos eventos agora sim.
