### ISSUE TITLE
Atualização com necessidade de QRCode

### ISSUE THREAD

**Issue by arthurnobrega** [andreroggeri/pynubank#29]
Olá!

Tenho um fork do código do Astrocoders e percebi que o Nubank começou a pedir um QRCode no site online para dar acesso à API, isso fez com que nossa estratégia de acessar a API quebrasse.

Pode testar se está funcionando para vocês?

Tem alguma ideia de como fazer funcionar após essa alteração?

**Comment by andreroggeri** [comment]
Olá, acho que é uma funcionalidade que está em rollout. Para mim não houve nenhuma mudança, porém alguns usuários já relataram esse problema (#27)

Pelos comentários basta logar pelo browser que você conseguirá fazer o acesso pela api novamente.

**Comment by maronezzi** [comment]
Recebi também o erro, 

Traceback (most recent call last):
  File "sync.py", line 18, in <module>
    nu = Nubank(NUBANK_LOGIN, NUBANK_PASSWORD)
  File "/usr/local/lib/python3.6/dist-packages/pynubank/nubank.py", line 27, in __init__
    self.authenticate(cpf, password)
  File "/usr/local/lib/python3.6/dist-packages/pynubank/nubank.py", line 68, in authenticate
    raise NuException('Authentication failed. Login using NuBank website, make all steps of authentication and try again.')
pynubank.nubank.NuException: Authentication failed. Login using NuBank website, make all steps of authentication and try again.

Mesmo logando pelo site, o erro continua. Alguma sugestão de como corrigir?

**Comment by Lrcezimbra** [comment]
Mesmo problema aqui, não consigo mais usar a lib.
Acho que a issue deveria ficar aberta para buscarmos uma solução @andreroggeri

**Comment by jeffersonmsb** [comment]
@Lrcezimbra Acabei de utilizar e está funcionando. Não sei se é pq estou com uma versão antiga...
O que não deu certo foi em relação ao qrcode somente?

**Comment by Lrcezimbra** [comment]
@jeffersonmsb Sim, por causa do QR Code, essa nova autenticação não é para todos ainda, mas para quem já está ativa a lib para de funcionar.

**Comment by jeffersonmsb** [comment]
@Lrcezimbra Isso é ruim! Tem alguma maneira de impedir que isso seja ativado? Talvez seja ativado no primeiro uso.

**Comment by Lrcezimbra** [comment]
@jeffersonmsb no meu caso foi ativado há poucos dias. E há poucos dias também me liberaram a função débito. Se não foi uma coincidência, essa autenticação deve ser ativada junto com a função de débito.

**Comment by jeffersonmsb** [comment]
@leogregianin Eu tenho a função débito e já utilizei.

**Comment by Lrcezimbra** [comment]
@jeffersonmsb Ah, então deve ter sido só coincidência.

**Comment by davidkwast** [comment]
É recente mesmo. Mas depois de autenticado, mudou alguma coisa? Eu já fiz soluções que automação de API que embutem um navegador e pedem par ao usuário passar pelo CAPTCHA. Então eu faria uma que apresenta  QRCODE. Se for server-side, complica, mas não é impossível. Mas será bem desafiador enviar o QRCODE a tempo de não vencer.

**Comment by andreroggeri** [comment]
@davidkwast é uma opção... Eu queria ver como que o front recebe esse QRCode pra ver se conseguiriamos fazer isso sem o browser...

Outra coisa, seria ver se ao autenticar uma vez com o QRCode, como fazer com que o QRCode não seja mais necessário.

Se tivermos que escanear toda vez, acho que uma parte da utilidade da lib vai por agua abaixo. 😢

**Comment by Lrcezimbra** [comment]
Eu estava pensando em fazer algo como o @davidkwast, continuaria funcionando, mas aumentaria bastante o trabalho, pois teria que scanear o QR cada vez q fosse usar a lib :cry: 

Pelo que vi o QR Code é gerado no front, então teriamos que usar algo como Selenium para conseguir criar o QR. Mas tenho que dar uma investigada melhor nisso.

@andreroggeri No meu caso o QR Code é necessário em toda autenticação. Mesmo autenticando pelo browser eu não consegui usar a lib.

**Comment by andreroggeri** [comment]
Mas e no site? Você também precisa escanear toda vez ou uma vez que você
autenticou nas próximas ele não pede mais?

**Comment by Lrcezimbra** [comment]
@andreroggeri Acabei de testar isso. Cada vez precisei autenticar de novo. Se fecho a aba e abro em outra tenho que ler o QR Code novamente.

**Comment by jeffersonmsb** [comment]
@Lrcezimbra como vc fez? 
Mesmo precisando do qrcode todas ainda seria útil pra mim.

**Comment by andreroggeri** [comment]
Agora o site tb tá pedindo o scan do QRCode pra mim tb. 😢 

Vou ver se consigo gerar essa cara no console

**Comment by andreroggeri** [comment]
Vi aqui que o QRCode é só o valor da variável `window.sessionStorage.sessionID`.

Precisa ver como que esse ID é gerado, a partir disso podemos printar o QRCode no terminal (Vi que tem algumas libs pra isso) pra escanear com o app do nubank.

Se isso der certo, faz mto sentido implementar o cache de token / refresh

**Comment by andreroggeri** [comment]
Turma, fiz uma implementação parcial com suporte pro QRCode na branch `fix-qr-code`.
Antes do meu teste eu fui bloqueado 😢 

Se alguém puder testar seria top !

**Comment by andreroggeri** [comment]
Pra instalar direto o código dessa branch é só usar esse comando: `pip install git+https://github.com/andreroggeri/pynubank.git@fix-qr-code`

**Comment by andreroggeri** [comment]
Passando pra avisar que não funciona ! 🤣 
`TypeError: 'NoneType' object is not subscriptable`

**Comment by andreroggeri** [comment]
Resolvido... @jeffersonmsb consegue testar pra validar a solução ? 👍

**Comment by Lrcezimbra** [comment]
Funcionou!!!!

**Comment by andreroggeri** [comment]
Aew!! Pelo menos parte da funcionalidade está de volta. 😝

Agora pra voltar a ser o que era antes, precisa ver se conseguimos imitar o fluxo do App, onde primeiro é enviado um e-mail pra autorizar o App, depois ele fica livre pra fazer outras consultas...

**Comment by jeffersonmsb** [comment]
> Resolvido... @jeffersonmsb consegue testar pra validar a solução ?

Funcionando!

Contabilidade atualizada novamente!
Valeu, espero um dia poder ajudar em algo.

**Comment by andreroggeri** [comment]
Valeu turma !

Vou escrever uns testes e publicar a 0.18 ! 😃

**Comment by lira92** [comment]
@andreroggeri gostaria de agradecer por ter feito essa implementação da autenticação usando QRCode, me baseei nela pra dar suporte ao client que criei pra .net: https://github.com/lira92/nubank-dotnet.

**Comment by andreroggeri** [comment]
Top demais @lira92

Uma dica: eu achei um jeito de continuar autenticando sem o QRCode. O código já tá na master, vc pode dar uma olhada...

Basicamente se vc autenticar com CPF / Senha, pegar o refresh_token e autenticar novamente continua funcionando. (não sei até quando o Nubank vai permitir, então mantive a autenticação com QRCode)

**Comment by lira92** [comment]
@andreroggeri legal cara, vou olhar sim, isso vai ser de grande ajuda pra mim 😄
