### ISSUE TITLE
nu.get_account_statements() retornando NuRequestException: The request made failed with HTTP status code 403

### ISSUE THREAD

**Issue by Tianoklein** [andreroggeri/pynubank#290]
Ao tentar retornar os dados da NuConta:

nu.get_account_statements()

`---------------------------------------------------------------------------
NuRequestException                        Traceback (most recent call last)
<ipython-input-22-8cd9d081407c> in <module>()
----> 1 nu.get_account_statements()

~/.local/lib/python3.7/site-packages/pynubank/nubank.py in get_account_statements(self)
    169 
    170     def get_account_statements(self):
--> 171         feed = self.get_account_feed()
    172         feed = map(parse_pix_transaction, feed)
    173         return list(filter(lambda x: x['__typename'] in PAYMENT_EVENT_TYPES, feed))

~/.local/lib/python3.7/site-packages/pynubank/nubank.py in get_account_feed(self)
    165 
    166     def get_account_feed(self):
--> 167         data = self._make_graphql_request('account_feed')
    168         return data['data']['viewer']['savingsAccount']['feed']
    169 

~/.local/lib/python3.7/site-packages/pynubank/nubank.py in _make_graphql_request(self, graphql_object, variables)
     45     def _make_graphql_request(self, graphql_object, variables=None):
     46         return self._client.post(self._query_url,
---> 47                                  json=prepare_request_body(graphql_object, variables))
     48 
     49     def _password_auth(self, cpf: str, password: str):

~/.local/lib/python3.7/site-packages/pynubank/utils/http.py in post(self, url, json)
     44 
     45     def post(self, url: str, json: dict) -> dict:
---> 46         return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))

~/.local/lib/python3.7/site-packages/pynubank/utils/http.py in _handle_response(self, response)
     33     def _handle_response(self, response: Response) -> dict:
     34         if response.status_code != 200:
---> 35             raise NuRequestException(response)
     36 
     37         return response.json()

NuRequestException: The request made failed with HTTP status code 403

`

**Comment by andreroggeri** [comment]
Chegou a dar uma olhada na #285 ?

Aparentemente o acesso com QRCode não está mais permitindo o acesso a parte da NuConta.

**Comment by jeffersonmsb** [comment]
Aparentemente ontem houve um instabilidade. Notei isso tanto no app quanto no acesso pela API.

O problema persiste?
