### ISSUE TITLE
OAuth2 pix

### ISSUE THREAD

**Issue by j0mba** [andreroggeri/pynubank#292]
Bom dia,

Teria alguma iniciativa do projeto para a implementação do OAuth2 em vez de passar o CPF e as senhas no método das credenciais? visto que o bacen ta com a OpenAPI já divulgada.

**Comment by andreroggeri** [comment]
Não que eu saiba.

Toda a implementação feita aqui foi feita em cima das APIs que o site e o App usam. (lembrando que uma vez que vc loga com cpf/senha vc consegue um refresh token que pode ser utilizado nos logins subsequentes) 

Me corrija se eu estiver errado, mas as APIs do BACEN não serão "abertas" (muito provavelmente os bancos irão cobrar pois eles controlam o acesso) e muito mais voltada para empresas

**Comment by j0mba** [comment]
O bacen ta com uma openapi, https://github.com/bacen/pix-api. Eles utilizam o OAuth2 para autenticação, o que é necessário é gerar uma transação no PSP, já ta implementada a parte de gerar uma transação, então isso seria uma implementação para integrar tudo. To estudando este tema a pouco tempo, posso ter falado besteira, mas acho que seria uma ideia.

**Comment by andreroggeri** [comment]
Sim, essa é a especificação e os bancos implementam.

A parte de gerar uma transação que usamos aqui foi feita replicando o App, mas não é usando uma api publica que respeita a especificação do BACEN.

Meu entendimento é que a api interna que o App consome e a api publica são coisas diferentes.

**Comment by j0mba** [comment]
É que eu vi um gerador de QrCode para PIX, então pensei que seria algo público. Segue o site.

https://www.gerarpix.com.br/

**Comment by andreroggeri** [comment]
Isso, mas é tudo "offline" nesse caso

> Para a geração do QRcode Estático não é feita nenhuma integração com o sistema PIX e bancos, é apenas uma forma de demostrar os dados PIX do pagador em um QrCODE, utilizando o padrão BRCode

**Comment by j0mba** [comment]
Entendi, valeu então @andreroggeri
