### ISSUE TITLE
Adicionar identificador de transação na função get_account_statements

### ISSUE THREAD

**Issue by mateusbarros92** [andreroggeri/pynubank#295]
É possível adicionar o identificador da transação pix na querie get_account_statements?
Esse identificador é importante pois com ele é possível determinar se um pagamento pix gerado pela própria API foi pago.

**Comment by mateusbarros92** [comment]
Esse identificador é o mesmo que passamos como último parâmetro na chamada da função create_pix_payment_qrcode.

**Comment by andreroggeri** [comment]
Que eu saiba não, a api não retorna muitos detalhes na listagem de transações.

Pra obter essa informação é necessário chamar o método   que trás esse detalhe da transação. Mas pra isso é necessário fazer uma chamada pra api pra cada transação

**Comment by andreroggeri** [comment]
O método que trás essa informação é o `get_pix_identifier`

**Comment by mateusbarros92** [comment]
Obrigado!
