### ISSUE TITLE
Suporte a conta PJ

### ISSUE THREAD

**Issue by jrobertojunior** [andreroggeri/pynubank#304]
Seria legal dar suporte a contas jurídicas. Existe alguma forma de fazer isso?

**Comment by andreroggeri** [comment]
Quando eu tentei fazer isso, esbarrei no problema de que a conta PJ parece ter mais mecanismos de segurança e nunca consegui gerar o token diretamente.


Como não tenho conta PJ não consigo validar se isso ainda tá valendo, mas se alguém quiser tentar.

Na #139 tem bastante informação de como pegar os requests

**Comment by pecampelo** [comment]
Eu estou utilizando o pacote teu, parabéns aliás. 

Se eu conseguir vou informando.

> Quando eu tentei fazer isso, esbarrei no problema de que a conta PJ parece ter mais mecanismos de segurança e nunca consegui gerar o token diretamente.
> 
> Como não tenho conta PJ não consigo validar se isso ainda tá valendo, mas se alguém quiser tentar.
> 
> Na #139 tem bastante informação de como pegar os requests

**Comment by pecampelo** [comment]
Info: Aparentemente, o fluxo do Nubank PJ é agora parte do fluxo PF também. No celular, o usuário entra primeiro na conta PF, depois seleciona para entrar na conta PJ associada.

**Comment by arthurbarros** [comment]
@pecampelo teve alguma evolucao ai com a PJ ?

**Comment by pecampelo** [comment]
@arthurbarros cara, precisa de uma gravação de vídeo do rosto do detentor da conta com ângulos diferentes sincronizando com a API do nubank em requisições com mais infos tipo o nubank PJ. Machine learning pode dar conta mas me parece um trabalho exorbitante.

**Comment by MrPowerGamerBR** [comment]
@pecampelo eu estava pensando neste problema, será que não seria possível pegar o ID/token da sessão gerado pelo app para autenticar pela lib? Assim você não teria que fazer todo o flow de login, exceto se o token for invalidado. Afinal, você não precisa fazer o processo de segurança toda hora que você acessa a conta, parece que só precisa fazer isso ao logar pela primeira vez na conta em um novo dispositivo, mas posso estar errado sobre isso.

**Comment by pecampelo** [comment]
Creio que você precisa ver como funcionam as requisições deste pacote de fato, esse token que vc está caracterizando aí é o certificado, que só precisa ser gerado uma vez mesmo, e nas próximas sessões já está autorizado. 

A parte do PJ está atrás dessa autorização que deve ser por websockets (estou supondo aqui, é como eu implementaria), e não vejo muito a ideia de um token aí.

Pelo menos agora eles dissociaram a conta PJ da conta PF, mas não tenho uma PJ para desenvolver o resto do user flow, infelizmente.

**Comment by andreroggeri** [comment]
É possível extrair o certificado e o token do dipositivo sim, mas realmente seria necessário ter root no aparelho.

Quando testei isso há 2 anos, o resto dos endpoints funcionaram normalmente.
