### ISSUE TITLE
Erro na autenticação

### ISSUE THREAD

**Issue by joaomunarim** [andreroggeri/pynubank#307]
Oi! Primeiramente, parabéns pelo projeto.

Rodei esse código meses atrás e deu tudo certo, porém, rodando agora recebi um erro na autenticação do CPF e senha:

![image](https://user-images.githubusercontent.com/39132386/157577291-e74c4f65-f4a0-4806-a459-083f8017b02d.png)

Estou rodando no Jupyter. Saberia dizer o porquê disso?

Obrigado!

**Comment by andreroggeri** [comment]
Recentemente o Nubank atualizou o esquema de autenticação.
Você tá fazendo login com qr code, então você só vai conseguir acessar a
parte do cartão de crédito (no site não dá Nu não tem a parte da nuconta)

Pra resolver isso você precisa gerar o certificado e autenticar com ele.

Em qua., 9 de mar. de 2022 23:38, joaomunarim ***@***.***>
escreveu:

**Comment by joaomunarim** [comment]
Funcionou perfeitamente. Obrigado!
