### ISSUE TITLE
Bloqueado após uma requisição.

### ISSUE THREAD

**Issue by jeffersonmsb** [andreroggeri/pynubank#31]
Estou sendo bloqueado após uma requisição.
Alguém está tendo o mesmo comportamento?

Recebo "Authentication failed. Too Many Requests (429)".

**Comment by jeffersantoss** [comment]
Faça apenas uma requisição para obter o token.. Após isso use o token para fazer quantas requisições quiser em outras rotas. Muitas requisições na rota de login causam esse erro por questões de segurança do Nubank pois eles podem entender como um ataque...

**Comment by andreroggeri** [comment]
☝️

**Comment by jeffersonmsb** [comment]
Eu não entendi muito bem a parte de fazer requisições em outras rotas.
Mas eu salvei o token e todo resto pra não realizar login todas as vezes.
Não fui mais bloqueado. Deu certo!

Valeu pessoal.

**Comment by joubertredrat** [comment]
Só uma dúvida relacionado ao bloqueio. Caso eu seja bloqueado, as transações no meu cartão será negados ou somente o login que é bloqueado?

**Comment by andreroggeri** [comment]
Somente o login é bloqueado =]

Isso acontece principalmente quando vc faz mtos logins por QRCode.

Ainda não aconteceu comigo de ser bloqueado no login por certificado.

Em sáb, 13 de jun de 2020 01:18, Joubert RedRat <notifications@github.com>
escreveu:
