### ISSUE TITLE
Transações de compra de NUBR33

### ISSUE THREAD

**Issue by mateusglucas** [andreroggeri/pynubank#318]
Eu estou tentando calcular o saldo da minha conta usando o `nu.get_account_statements()`. Quase fecha, se não fosse as transações que fiz para compra de BRDs. Elas não aparecem no `nu.get_account_statements()`, só no `nu.get_account_feed()` como GenericFeedEvent e mesmo no feed não aparece nenhuma indicação do valor nos detalhes. Alguém tem alguma ideia de como obter o valor dessas transações?

**Comment by andreroggeri** [comment]
Daria para fazer algo parecido como foi feito para as transações pix que também são `GenericFeedEvent`.

O código está aqui: https://github.com/andreroggeri/pynubank/blob/25b0897fdd2bd68197114f01b27fe195e5fbe46a/pynubank/utils/parsing.py#L22

**Comment by mateusglucas** [comment]
Pois é, eu tinha dado uma olhada no que é feito pro pix. O problema é que pra essas transações não tem nenhuma informação de valor no campo `detail`.

**Comment by andreroggeri** [comment]
Hmm, eu cheguei a dar uma olhada no app e lá ele mostrava o valor que foi
adquirido. Mais tarde vou ver como que está sendo retornado da api

Em ter., 10 de mai. de 2022 00:00, mateusglucas ***@***.***>
escreveu:

**Comment by mateusglucas** [comment]
Eu até tentei seguir as dicas em #139 pra rodar o emulador e pegar os pacotes, mas não to conseguindo. Consigo instalar o Google Play pelo OpenGApps mas depois disso a tela do emulador começa a se apagar, fica reiniciando a imagem e não consigo fazer mais nada.

**Comment by andreroggeri** [comment]
Com a ajuda do @mateusbarros92 e do @Bezouro agora é possível recuperar as transações de forma paginada. Nessa implementação teoricamente sempre vai vir o campo `value` (que é extraído do detalhe da transação)
