### ISSUE TITLE
PIX RECEBIDOS - get_pix_identifier (retornar os 100 últimos identificdor)

### ISSUE THREAD

**Issue by isomiluizdasilva** [andreroggeri/pynubank#330]
estou na fissura de fazer funcionar o retorno dos 100 últimos IDENTIFICADOR de pix recebidos na conta NUBANK, pretendo executar o script a cada 10 minutos e gerar um arquivo JSON, sei que para o amigo que é fera em PYTHON é moleza, mas para mim, estou quebrando cabeça aqui :) :) :).

Estou usando o código (com meus identificadores):
--- CÓDIGO USADO
```
import json
from pynubank import Nubank, MockHttpClient

nu = Nubank(MockHttpClient())
nu.authenticate_with_qr_code('some-cpf', 'some-password', 'some-uuid')

transactions = nu.get_account_statements()

for transaction in transactions[:100]:
    tx_status = nu.get_pix_identifier(transaction['id'])
    # Poderá retornar None caso a transação não seja Pix ou não tiver identificador
    # Caso contrário retorna o identificador único que foi cadastrado no QRCode
    with open(f'feed_identificadores.json', 'w') as f:
        json.dump(tx_status, f)
    print(tx_status) 
```
--- CÓDIGO USADO

--- CÓDIGO QUE USAREI PARA A TAREFA
```
import sched
scheduler = sched.scheduler()

def printa():
    print("AQUI COLOCAREI A FUNÇÃO E ALTERAREI O TEMPO PARA 10 MINUTOS")
    scheduler.enter(delay=5, priority=0, action=printa)
    
printa()

scheduler.run(blocking=True)
```
--- CÓDIGO QUE USAREI PARA A TAREFA

**Comment by andreroggeri** [comment]
Não entendi a dúvida.

Para dúvidas gerais sobre python recomendo usar o stackoverflow.com ou pt.stackoverflow.com
