### ISSUE TITLE
Investimentos e attributos listados errados

### ISSUE THREAD

**Issue by fernandorovai** [andreroggeri/pynubank#336]
Parece que a query para pegar as RDB's / investimentos (nu.get_account_investments_details()) mudou, estou recebendo vários campos vazios como esse:
'redeemedBalance': {'netAmount': 0.0,
   'yield': 0.0,
   'incomeTax': 0.0,
   'iofTax': 0.0}

Nos casos em que não estão vazios, os valores não batem com o app. Alguém consegue dar um sniff na query? Posso mandar um PR com a mundaça, caso precisar.

**Comment by andreroggeri** [comment]
Vou tentar pegar aqui...

**Comment by andreroggeri** [comment]
Parece que vai ser um pouco mais dificil do que só atualizar a query.

Aparentemente a request dessa tela é gRPC (Que eu tenho 0 conhecimento), teria que ver como fazer uma engenharia reversa desse response da uma definição de response =/
<img width="635" alt="image" src="https://user-images.githubusercontent.com/6232673/181016752-16a239d0-fb2c-4b8b-b3ea-f79d88174225.png">

Toda ajuda é bem vida
