### ISSUE TITLE
realizar pagamento PIX

### ISSUE THREAD

**Issue by alexandrechoske** [andreroggeri/pynubank#338]
OPa @andreroggeri blz?
Teria como realizar um pagamento por PIX, tendo um código?

Por ex:

Tenho a lista de códigos dos PIX da minha fatura, gostaria de rodar um script para pegar este código e realizar o pgto.

Vlwwwwwwww

**Comment by andreroggeri** [comment]
Não. A lib não consegue fazer nenhuma operação financeira pq precisaria fazer o processo de envio da selfie.

**Comment by alexandrechoske** [comment]
blz obrigado!!
