### ISSUE TITLE
Após a versão 2.17.0 campo __typename retornando somente "GenericFeedEvent"

### ISSUE THREAD

**Issue by lpsouza** [andreroggeri/pynubank#339]
Uso a função `get_account_feed()` para obter os lançamentos em conta e desde a versão 2.18.0 que o campo `__typename` só está retornando o tipo "GenericFeedEvent". Outra coisa que notei é que quando não existe o campo `amount` eu buscava o valor no campo `details`, mas o valor não aparece mais ali. Então diversos registros ficam sem o valor.

A solução que fiz aqui e resolveu (para a minha aplicação) foi congelar a versão na 2.17.0.

Esses comportamentos novos estão corretos? Alterou algo na forma ou tratamento dos dados?

Ah sim, uma última observação: nas versões recentes (2.18.0 em diante), se uso a função `get_account_statement()` (que deixei de usar desde a issue #217) agora só retorna transações de PIX e não mais outras transações (TED, Pagamentos de boletos, etc).

**Comment by andreroggeri** [comment]
O app do Nubank passou a usar outra query para montar a tela de transações, onde agora as informações vem paginadas ao invés de vir tudo de uma vez. Com isso essa query do `get_account_feed` / `get_account_statements` começou a retornar menos informações para as transações mais novas.

Para suportar a paginação foi feito [essa mudança](https://github.com/andreroggeri/pynubank/pull/326/files) que provavelmente acabou quebrando o método não paginado.

Acredito que uma solução temporária para continuar usando o método antigo (Mas vai continuar não trazendo os dados para as transações mais novas) seja essa:

```python
http = HttpClient()
http.set_header('X-Correlation-Id', 'WEB-APP.pewW9')
nu = Nubank(client=http)
nu.get_account_statement() # Deve funcionar da mesma forma como na 2.17.0
```

**Comment by lpsouza** [comment]
Obrigado pelo esclarecimento, vou estudar a nova implementação pra adaptar a minha realidade aqui.
