### ISSUE TITLE
Erro no get_account_statements() em determinadas accounts

### ISSUE THREAD

**Issue by monrapps** [andreroggeri/pynubank#341]
Estou tendo esse erro em algumas accounts: 
`nubank.py", line 198, in get_account_statements
    feed = map(parse_pix_transaction, feed)
TypeError: 'NoneType' object is not iterable`

Ja na versão 2.19.1

**Comment by andreroggeri** [comment]
Se você executar o `get_account_feed` o que ele retorna ?

**Comment by monrapps** [comment]
`get_account_feed ` retorna o json com o feed corretamente

**Comment by monrapps** [comment]
testando na versão 2.20 não estou mias conseguindo reproduzir o erro. reabro caso venha a conseguir.

**Comment by monrapps** [comment]
O problema voltou... apenas uma das accounts da ele

` File "./teste.py", line 9, in <module>
    print(nu.get_account_statements())
  File "/usr/local/lib/python3.9/site-packages/pynubank/auth_mode.py", line 23, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pynubank/nubank.py", line 206, in get_account_statements
    feed = map(parse_pix_transaction, feed)
TypeError: 'NoneType' object is not iterable
`

ja o print(get_account_feed()) retorna "None" e nao quebra

**Comment by andreroggeri** [comment]
Essa conta tem alguma movimentação ? Estranho o feed ser `None`

**Comment by monrapps** [comment]
essa conta tem muita movimentação.. recebe muito pix.

**Comment by andreroggeri** [comment]
Então deve ser algum comportamento do Nubank.

Esse endpoint não é mais utilizado pelo app, e sim o paginado... Você consegue testar nele ? É o `get_account_feed_paginated`

**Comment by monrapps** [comment]
esse get_account_feed_paginated() funcionou ... baixou 50 pages.

**Comment by alexandrechoske** [comment]
@andreroggeri tem planos para trazer os dados das caixinhas?
percebi que estando nas caixinhas o valor não vem ;/

**Comment by andreroggeri** [comment]
@monrapps perfeito, então precisamos depreciar esse método aqui pq ele já está deixando de funcionar corretamente

**Comment by andreroggeri** [comment]
@alexandrechoske não, eu tenho usado bem pouco o Nubank, mas PRs são bem vindos

**Comment by monrapps** [comment]
@andreroggeri qual seria a melhor estratégia aqui ?? 
- criar um `get_account_statements_paginated()`
- fazer o `get_account_statements()` rodar todas as pages dando append e retornar tudo

**Comment by lipemorais** [comment]
Eu vim aqui falar disso também. Tenho um script que roda toda noite para pegar minhas transações e começou a falhar também. Me parece o mesmo motivo.
https://github.com/lipemorais/financas-automatizadas/actions/runs/3179127061/jobs/5181310183

Sobre qual seria e melhor estratégia eu gosto de manter ao máximo a retro compatibilidade, então faria os 2. Dando prioridade para o novo `get_account_statements`.

1. fazer o get_account_statements() rodar todas as pages dando append e retornar tudo
1. criar um get_account_statements_paginated()

**Comment by andreroggeri** [comment]
Como o `get_account_statements` "antigo" ainda funciona para algumas pessoas (Aqui ainda funciona) e ele retorna uma entidade diferente do novo, o ideal seria criar um método novo e depreciar isso.

Poderiamos criar um `get_account_statements_paginated` trazendo somente as transações que contém o campo `amount` (Que tentamos extrair de vários campos). O que acham ?

**Comment by andreroggeri** [comment]
Sobre trazer todas as páginas, eu tenho sentimentos mistos, pq no caso da lib fazer várias chamadas de API e acabar bloqueando a conta (Não sei como tá isso hoje), seria na nossa conta. Por isso [eu deixei um exemplo](https://github.com/andreroggeri/pynubank/blob/main/examples/extract-all-paginated-feed-pages.md#buscando-todas-as-p%C3%A1ginas) de como pegar todas a páginas ao invés de implementar dentro da lib, assim a responsabilidade fica com quem está usando.

**Comment by lipemorais** [comment]
>Como o get_account_statements "antigo" ainda funciona para algumas pessoas (Aqui ainda funciona) e ele retorna uma entidade diferente do novo, o ideal seria criar um método novo e depreciar o antigo.

Entendi. Parece o melhor caminho mesmo.

**Comment by monrapps** [comment]
De acordo. @andreroggeri você vai implementar ou está esperando eu fazer ?

**Comment by andreroggeri** [comment]
Implementado na #348 

Agora os métodos `get_account_feed` e `get_account_statements`estão deprecated e tb criei o `get_account_statements_paginated` que retorna o feed só de transações que tem valor (Excluindo aquela "Bem vindo ao Nubank" por ex)
