### ISSUE TITLE
Identificar entrada/saída no get_account_feed_paginated

### ISSUE THREAD

**Issue by meciasbueno** [andreroggeri/pynubank#345]
O retorno do feed paginado não tem o campo **__typename** para identificar se é entrada ou saída.
Eu vi que o array **tags** tem um item com **money-out/money-in**
Dá para confiar nesse **tags**? qual campo vocês estão usando para identificar?

**Comment by andreroggeri** [comment]
Ainda não precisei, mas parece que o tags é o ideal mesmo.
