### ISSUE TITLE
App não está lendo o QR code 

### ISSUE THREAD

**Issue by andrei258258** [andreroggeri/pynubank#36]
Pessoal, o meu app não consegue ler o QR code gerado pela lib (no site está normal). 
![Screenshot_11](https://user-images.githubusercontent.com/22275358/55395884-ede08080-5518-11e9-9731-5e5094a1e524.png)
O app simplesmente não reconhece nenhum QR na tela :(
App no release do dia 25/03/19

**Comment by jeffersonmsb** [comment]
Não é por causa da cor invertida no qr code?

Em ter, 2 de abr de 2019 07:30, Andrei Donati <notifications@github.com>
escreveu:

**Comment by andreroggeri** [comment]
Do jeito que tá renderizando no jupyter o App não vai conseguir ler mesmo... Dá pra gerar em png nesse caso..

**Comment by andrei258258** [comment]
@jeffersonmsb Na minha tela não aparecia estas linhas coloridas (apareceu somente no print)
@andreroggeri Alguma sugestão de outra IDE para gerar o Qr Code?

**Comment by andreroggeri** [comment]
@andrei258258 eu testei direto no console, nem lembrei do jupyter...

**Comment by andreroggeri** [comment]
@andrei258258 consegui uma solução aqui... Vou escrever uns testes e subir ! 👊

**Comment by andreroggeri** [comment]
Funcionou 🎊  

![image](https://user-images.githubusercontent.com/6232673/55768512-9039c000-5a53-11e9-9269-f1edcbad28fd.png)
