### ISSUE TITLE
Geração de certificado está falhando

### ISSUE THREAD

**Issue by cobap** [andreroggeri/pynubank#360]
Olá, tentei fazer a geração do certificado, mas recebo um erro de modulo depreciado. Alguém conseguiu resolver isso?

![image](https://user-images.githubusercontent.com/6344807/200124199-075e1fe1-6acf-4c4f-9e75-3085fa78af7c.png)

**Comment by andreroggeri** [comment]
Corrigido na 2.21.1

**Comment by cobap** [comment]
Obrigado Andre!
