### ISSUE TITLE
Há algum campo com o cartão de crédito de origem?

### ISSUE THREAD

**Issue by WittmannF** [andreroggeri/pynubank#389]
Olá! Parabéns pelo projeto.

Gostaria de saber se há algum campo que contém os últimos digitos ou algum identificador de qual cartão de crédito foi usado? Eu possuo uns 5 cartões virtuais, e gostaria de diferenciar os gastos de cada um. Os campos que tenho no momento são:
```
description | category | amount | time | source | title | amount_without_iof | account | details | id | _links | tokenized | href
```

Obrigado

**Comment by andreroggeri** [comment]
Tem sim, mas você precisa fazer uma chamada pra cada transação =T

```python
statements = nu.get_card_statements()
details = nu.get_card_statement_details(statements[0])

print(details['transaction']['mcc']) # 4899
```

**Comment by WittmannF** [comment]
Ok, interessante! Será que corro o risco de ser bloqueado por realizar várias chamadas?

**Comment by andreroggeri** [comment]
[Aqui](https://github.com/andreroggeri/pynubank/discussions/352) tem uma discussão sobre o rate limit.

Talvez uma alternativa seja olhar na fatura.

**Comment by WittmannF** [comment]
Excelente! Obrigado André!
