### ISSUE TITLE
Como visualizar o limite disponível do cartão de crédito?

### ISSUE THREAD

**Issue by Evandromsousa** [andreroggeri/pynubank#392]
Olá,  gostaria de saber se a biblioteca tem alguma função parecida com o (get_account_balance() = mostra o saldo da conta bancaria ) mas para mostrar o limite disponível no crédito? ou como fazer para conseguir ver o limite disponivel no crédito através da biblioteca
Desde já agradeço

**Comment by andreroggeri** [comment]
Acredito que não temos implementado essa parte ainda. 

PRs são bem vindos

**Comment by CTXO** [comment]
Olá, creio que essa funcionalidade já existe no projeto através da função `get_credit_card_balance`. Ela retorna um dicionário em que a chave `available` mostra o limite disponível no crédito e a chave `open` mostra seus gastos no crédito em aberto. 

Segue exemplo no código: 
``` python
from pynubank import Nubank, MockHttpClient
nu = Nubank(MockHttpClient())
nu.authenticate_with_cert('12345678910', '23442323', 'README.md')
cc_data = nu.get_credit_card_balance()
print(f"Dados cartão de crédito: {cc_data}")
print(f"Limite disponível: {cc_data['available']}")
```

Output:
``` bash
Dados cartão de crédito: {'prepaid': 0, 'due': 0, 'open': 0, 'available': 15000, 'future': 0}
Limite disponível: 15000

```

**Comment by andreroggeri** [comment]
Valeu @CTXO
