### ISSUE TITLE
Quando pretendem criar uma funcionalidade para pagamentos via PIX ?

### ISSUE THREAD

**Issue by Mordisquinha** [andreroggeri/pynubank#397]

**Comment by andreroggeri** [comment]
Improvável de ser implementado pelos motivos explicados [aqui](https://github.com/andreroggeri/pynubank/issues/183#issuecomment-738444849).

**Comment by Mordisquinha** [comment]
Putz, entendi, poderia enviar a doc da API que você usa ?

**Comment by andreroggeri** [comment]
Não tem documentação, todas as requests são obtidas [através de engenharia reversa](https://github.com/andreroggeri/pynubank/discussions/325)

**Comment by Mordisquinha** [comment]
entendi... Vou dar uma pesquisada com o Wireshark e fazer uns testes. BTW, excelente trampo mano, uso muito seu repo !

**Comment by anhaabaete** [comment]
Acho que posso contribuir, sou programador desde dos anos 90, só não tenho muita experiência em Python. Como faço para debugar? Porque seu eu clonar o repositório e chamar a lib ele executa a lib instalada e não a do repositório.

**Comment by CTXO** [comment]
> Acho que posso contribuir, sou programador desde dos anos 90, só não tenho muita experiência em Python. Como faço para debugar? Porque seu eu clonar o repositório e chamar a lib ele executa a lib instalada e não a do repositório.

Não sei seentendi muito bem o que vc quis dizer com "chamar a lib". Seria executar o comando `pynubank` para a geração do certificado? Se for isso, é só executar o arquivo `cli.py` dentro da pasta `pynubank`.
