### ISSUE TITLE
Possibilidade de verificar se um pix foi recebido na conta.

### ISSUE THREAD

**Issue by MTHS1901** [andreroggeri/pynubank#403]
É possível criar uma API para verificar se um pix foi recebido na conta? Verificando pelo NOME ou REFERÊNCIA de pagamento?

**Comment by andreroggeri** [comment]
[Aqui](https://github.com/andreroggeri/pynubank/blob/main/examples/pix.md#obtendo-o-identificador-de-uma-transa%C3%A7%C3%A3o)

**Comment by MTHS1901** [comment]
> [Aqui](https://github.com/andreroggeri/pynubank/blob/main/examples/pix.md#obtendo-o-identificador-de-uma-transa%C3%A7%C3%A3o)

Vc programa em PHP também? Como posso entrar em contato com vc pra solicitar o desenvolvimento de algo semelhante em php? Eu gostaria de receber um pagamento e em seguida verificar se o pagamento foi feito atravéz da referência.

**Comment by andreroggeri** [comment]
Talvez seja mais fácil utilizar a [implementação em PHP](https://github.com/nexy/phpnubank)
