### ISSUE TITLE
(WSL) Erro ao tentar requisitar um código via email

### ISSUE THREAD

**Issue by RNT17** [andreroggeri/pynubank#405]
Boa noite pessoal.

A algum tempo atrás consegui executar perfeitamente o pynubank no meu WSL (Uso windows).

Fui criar uma automação e hoje não estou conseguindo requisitar o código via email pra gerar um certificado.
Já testei meu cpf e senha pelo site e consigo fazer login, ou seja minha senha esta ok.

quando executo o pynubank:

[*] Starting PyNubank context creation.
[*] Generated random id: j41fsdf3nlez
[>] Enter your CPF(Numbers only): ***********
[>] Enter your password (Used on the app/website):
[*] Requesting e-mail code
[*] Failed to request code. Check your credentials!

**Comment by andreroggeri** [comment]
Duplicado da #400
