### ISSUE TITLE
Erro no método get_bill_details

### ISSUE THREAD

**Issue by VictorOlimpio** [andreroggeri/pynubank#414]
Estou me deparando com o seguinte erro quando tento usar esse método:

`KeyError: 'self'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[40], line 4
      1 bills = nu.get_bills()
      3 # Retorna um dicionário contendo os detalhes de uma fatura retornada por get_bills()
----> 4 bill_details = nu.get_bill_details(bills[1])
File c:\Users\950604\workspace\finance_plan\env\lib\site-packages\pynubank\auth_mode.py:23, in requires_auth_mode.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     18 if instance._auth_mode not in required_auth_mode:
     19     raise NuInvalidAuthenticationMethod(
     20         'The authentication method used doest not allow access to this resource'
     21     )
---> 23 return function(*args, **kwargs)
File c:\Users\950604\workspace\finance_plan\env\lib\site-packages\pynubank\nubank.py:198, in Nubank.get_bill_details(self, bill)
    196 @requires_auth_mode(AuthMode.APP, AuthMode.WEB)
    197 def get_bill_details(self, bill: dict):
--> 198     return self._client.get(bill['_links']['self']['href'])
KeyError: 'self'`

Acredito que possa estar relacionado a autorização do dispositivo, nesse caso o pynubank, pois recebi um email dizendo q está limitando as funções desse dispositivo novo.

**Comment by andreroggeri** [comment]
Se você tiver faturas futuras esse método não funciona (acabei de descobrir 😅)

Você poe verificar se a fatura é futura ou não através do campo `state` se o valor for `future` não pode chamar essa função.

Preciso ajustar essa parte da documentação (PR's são bem vindos =] )
