### ISSUE TITLE
Refresh certificate

### ISSUE THREAD

**Issue by andreroggeri** [andreroggeri/pynubank#416]
O certificado expira após algum tempo.
Investigar se é possível gerar um novo com as credenciais atuais

**Comment by pfsmorigo** [comment]
Oi Andre. Conseguiu gerar o certificado, mesmo que provisório, depois que começou a dar o erro 401?

**Comment by andreroggeri** [comment]
Sim

**Comment by pfsmorigo** [comment]
Oi @andreroggeri , como você fez? Foi naquele esquema de usar o celular com root pra pegar o certificado? Teve que alterar o codigo do pynubank depois?

**Comment by andreroggeri** [comment]
A geração de certificado usando o pynubank continua funcionando, mas não temos a validação da selfie, então só funciona a parte do cartão.

Você quis dizer gerar o certificado que consegue acessar os dados da nuconta ?

**Comment by pfsmorigo** [comment]
Isso, pra acessar a nuconta

**Comment by renzon** [comment]
hoje, 10/11/2023, não consegui mais gerar o certificado. Então tentei a versão de autenticação via QR Code, mas também não consegui mais acessar as transações do cartão. Alguém achou uma solução?

**Comment by andreroggeri** [comment]
@renzon Poderia abrir uma issue separada?

**Comment by renzon** [comment]
Perdão André, funcionou. Acho que o Nubank bloqueou as primeiras vezes.
