### ISSUE TITLE
Por onde Começar para Replicar para a XP

### ISSUE THREAD

**Issue by WittmannF** [andreroggeri/pynubank#429]
Por curiosidade, caso queira replicar aos poucos para o banco XP, por onde começo? Qual ferramenta recomendariam para "ouvir" os requests que são feitos pelo APP durante autenticação. Tenho interesse em especial em ter acesso aos endpoints da fatura do cartão nas quais somente estão disponíveis via APP (a plataforma web é bem ruim e mais voltada para trading). 

Pesquisando na internet vi uma [sugestão de ferramenta chamada wireshark](https://stackoverflow.com/questions/20778072/sniffing-an-android-app-to-find-api-url). Vocês utilizam algo semelhante?

Obrigado

**Comment by andreroggeri** [comment]
Opa, já tem algo documentado [aqui](https://github.com/andreroggeri/pynubank/discussions/325).
Os mesmos passos devem se aplicar pra outros apps, mas podem haver outros mecanismos de segurança
