### ISSUE TITLE
pynubank.exception.NuRequestException: The request made failed with HTTP status code 401

### ISSUE THREAD

**Issue by JoaoVictorLong** [andreroggeri/pynubank#430]
![Erro_Nubank_1](https://github.com/andreroggeri/pynubank/assets/26606422/55e084ec-2dca-4e60-800f-821284bdd03a)

Estou fazendo o testo com o código base para autenticação com certificado, mas estou recebendo esse erro 401. Sabe se é algum erro recente? Estou usando Python 3.10

**Comment by andreroggeri** [comment]
Ver a #419
