### ISSUE TITLE
Erro 401 em requisições para a conta

### ISSUE THREAD

**Issue by roening** [andreroggeri/pynubank#453]
Olá, amigos!

Estou usando autenticação por certificado. Gerei o certificado com o comando `pynubank`, inserido as credenciais e o código recebido por email, e então consegui me autenticar usando ele, tanto que requisições como `get_customer` e `get_bills` funcionaram normalmente. Porém, todas requisições com prefixo `get_account_` estão falhando com 401.

Há algo que eu possa ter esquecido de fazer?

Após a geração do certificado recebi o email `Finalize a validação do seu dispositivo` informando que algumas funções estão temporariamente desativadas e que eu poderia seguir as instruções para liberá-las. Porém, esse dispositivo não é o app, mas sim meu script lol.

Alguma dica?

**Comment by andreroggeri** [comment]
O Nubank bloqueou o acesso as funcionalidades da Nuconta faz um tempo já. Ainda é possível usar a lib se você extrair o certificado da app. [Ver a issue pinada](https://github.com/andreroggeri/pynubank/issues/419)
