### ISSUE TITLE
Não consigo Gerar um Certificado

### ISSUE THREAD

**Issue by TuttaDaWeb** [andreroggeri/pynubank#454]
Olá, eu estou tentando gerar o Certificado para dar Certo mas está dando erro.
erro não, mas não estou conseguindo digitar a senha.

[*] Starting PyNubank context creation.
[*] Generated random id: xt750pqr3q2c
[>] Enter your CPF(Numbers only): 00000000001
[>] Enter your password (Used on the app/website):
[*] Requesting e-mail code
[*] Failed to request code. Check your credentials!

sabe a parte de "Enter your password (Used on the app/website)" então, eu não estou conseguindo digitar a senha.
eu já tentei de tudo mas estou conseguindo, tentei até colocar a pasta do PyNubank nas Variável do Sistema. mas não funcionou!
alguém pode me ajudar?

**Comment by andreroggeri** [comment]
O comportamento normal de aplicações CLI é não mostrar a senha digitada
(nem os asteriscos ) . Mas se você digitar ou colar a sua senha é para
funcionar.

Em seg., 15 de jul. de 2024, 09:00, TuttaDaWeb ***@***.***>
escreveu:

**Comment by TuttaDaWeb** [comment]
mas não está funcionando, serio! eu já tentei colar e digitar mas não está indo!

**Comment by andreroggeri** [comment]
Acabei de fazer um teste aqui e está funcionando:

```bash
➜  pynubank git:(main) ✗ pynubank
[*] Starting PyNubank context creation.
[*] Generated random id: w6jrjpwpa0ng
[>] Enter your CPF(Numbers only): 00000000001
[>] Enter your password (Used on the app/website):
[*] Requesting e-mail code
[*] Email sent to a**********@gmail.com
[>] Type the code received by email:
```


Você poder dar uma olhada na implementação do cli para passar a sua senha diretamente sem ser pelo terminal. [ref](https://github.com/andreroggeri/pynubank/blob/main/pynubank/cli.py)

**Comment by TuttaDaWeb** [comment]
eu tentei fazer isso agora pouco e não consegui, e não sei o porque não está funcionando! e fiz o que você sugeriu coloquei o cpf e senha direto pelo cli mas não deu CERTO! porque?
olha!:
[*] Starting PyNubank context creation.
[*] Generated random id: 6ph5e0iudyns
[>] Enter your CPF(Numbers only): 5********
[>] Enter your password (Used on the app/website): 16*********
[*] Requesting e-mail code
[*] Failed to request code. Check your credentials!

tem alguma coisa errado com o PyNubank

**Comment by andreroggeri** [comment]
Dificil ajudar sem ter mais detalhes. Você pode copiar o código do cli e no ponto que captura a exception e logar mais detalhes como o response e status code?

**Comment by TuttaDaWeb** [comment]
esse aqui é o Código do CLI.
import os
import random
import string
from getpass import getpass

from colorama import init, Fore, Style

from pynubank import NuException
from pynubank.utils.certificate_generator import CertificateGenerator


def generate_random_id() -> str:
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=12))


def log(message, color=Fore.BLUE):
    print(f'{color}{Style.DIM}[*] {Style.NORMAL}{Fore.LIGHTBLUE_EX}{message}')


def save_cert(cert, name):
    path = os.path.join(os.getcwd(), name)
    with open(path, 'wb') as cert_file:
        cert_file.write(cert.export())


def main():
    init()

    log(f'Starting {Fore.MAGENTA}{Style.DIM}PyNubank{Style.NORMAL}{Fore.LIGHTBLUE_EX} context creation.')

    device_id = generate_random_id()

    log(f'Generated random id: {device_id}')

    cpf = input(f'[>] Enter your CPF(Numbers only): 53823595806')
    password = getpass('[>] Enter your password (Used on the app/website): 1602Arthur')

    generator = CertificateGenerator(cpf, password, device_id)

    log('Requesting e-mail code')
    try:
        email = generator.request_code()
    except NuException:
        log(f'{Fore.RED}Failed to request code. Check your credentials!', Fore.RED)
        return

    log(f'Email sent to {Fore.LIGHTBLACK_EX}{email}{Fore.LIGHTBLUE_EX}')
    code = input('[>] Type the code received by email: ')

    cert1, cert2 = generator.exchange_certs(code)

    save_cert(cert1, 'cert.p12')

    print(f'{Fore.GREEN}Certificates generated successfully. (cert.pem)')
    print(f'{Fore.YELLOW}Warning, keep these certificates safe (Do not share or version in git)')


if __name__ == '__main__':
    main()

**Comment by TuttaDaWeb** [comment]
mas eu tenho uma pergunta? precisa de mais uma biblioteca para funcionar?
ou ter outras bibliotecas atrapalha?

**Comment by andreroggeri** [comment]
> mas eu tenho uma pergunta? precisa de mais uma biblioteca para funcionar?

Não, quando você instala o `pynubank`, todas as dependencias são instaladas junto

> ou ter outras bibliotecas atrapalha?

Em teoria não.

**Comment by TuttaDaWeb** [comment]
mas tem algo de errado com o CLI?

**Comment by TuttaDaWeb** [comment]
o que pode ser na sua opinião?

**Comment by andreroggeri** [comment]
O cli está funcionando aqui.

Se você postar aqui o response da API do Nubank ajuda a debugar o que está acontecendo.

**Comment by TuttaDaWeb** [comment]
tá mas a onde está a response do nubank? no arquivo nubank lá na pasta pynubank?

**Comment by TuttaDaWeb** [comment]
andré eu estou fechando por agora deu certo!
