### ISSUE TITLE
pynubank.exception.NuRequestException: The request made failed with HTTP status code 401 [POR FAVOR NÃO FECHA ESSE ISSUE]

### ISSUE THREAD

**Issue by TuttaDaWeb** [andreroggeri/pynubank#456]
Eu estou tendo um problema com o requests do pynubank, eu até fiz um issue mas o criador dessa pequena biblioteca fechou me comentário mas ele comentou sobre outro issue, no caso, isseu #419, mas eu, particular mente não estou consegui achar uma solução naquele issue. alguém pode achar para mim
o erro é esse:Traceback (most recent call last):
  File "C:\Users\arthu\OneDrive\Documentos\Projeto PyNubank\app.py", line 6, in <module>
    teste = nu.get_account_balance()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pynubank\auth_mode.py", line 23, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pynubank\nubank.py", line 235, in get_account_balance
    data = self._make_graphql_request('account_balance')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pynubank\nubank.py", line 52, in _make_graphql_request
    return self._client.post(self._query_url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pynubank\utils\http.py", line 49, in post
    return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pynubank\utils\http.py", line 35, in _handle_response
    raise NuRequestException(response)
pynubank.exception.NuRequestException: The request made failed with HTTP status code 401

POR FAVOR, NÃO FECHA ESSE ISSUE, E ME AJUDA A RESOLVER. É QUE EU NÃO CONSEGUI ACHAR NADA NO ISSUE #419 PARA RESOLVER ESSE PROBLEMA. PFV, ME AJUDA

**Comment by andreroggeri** [comment]
#419 ainda está aberta.
Para acessar os dados da Nuconta só é possível se você extrair o certificado do telefone (Pq precisa da verificação facial)

**Comment by TuttaDaWeb** [comment]
COMO ASSIM?
extrair o certificado pelo telefone?
