### ISSUE TITLE
Alguém pode me ajudar com o PyNubank

### ISSUE THREAD

**Issue by TuttaDaWeb** [andreroggeri/pynubank#459]
serio, galera!
eu não estou conseguindo fazer a requisição do Pynubank, o certificado, eu já gerei mas não consigo agora usá-lo pois fica dando erro e ninguém ta conseguindo me ajudar. POR FAVOR ALGUÉM ME AJUDA! o erro é o erro pynubank.exception.NuRequestException: The request made failed with HTTP status code 401! 
e no código está assim:
from pynubank import Nubank
from variables import cpf, passw

nu = Nubank()
nu.authenticate_with_cert(cpf, passw, 'caminho/cert.p12')
teste = nu.get_account_balance()

print(teste)
e antes que alguém venha cometar, eu sim coloquei os cpf e a senha, só que num variavel de outro arquivo.
POR FAVOR ALGUÉM ME AJUDA! e não encontrei nada aqui que possa me ajudar!

**Comment by andreroggeri** [comment]
@TuttaDaWeb Eu comentei sobre a #419, onde é necessário extrair o certificado do seu aparelho celular pois agora o Nubank exige a verificação facial para ter acesso a API da conta corrente. Lá naquela thread tem bastante informação de como algumas pessoas fizeram.
Eu mesmo não uso mais o `pynubank` pra acessar a conta corrente devido a isso. Só acesso os dados do cartão de crédito.

Infelizmente isso limitou bastante o uso do `pynubank`.

**Comment by TuttaDaWeb** [comment]
@andreroggeri isso é verdade! pois agora eu olhei na #419, e você precisa disso, é que eu quero usar o Pynubank, para fazer um sistema de pagamento com base no PIX com o microfremework Flask, eu escolhei o PyNubank pois sou menor de idade tenho 17 Anos mas apesar disso, o é um dos pouco bancos que permitem menores de idade, mas apesar disso, você poderia me dizer como posso fazer um sistema de pagamento? quais outros banco eu posso usar além deste? você poderia me indicar alguma biblioteca ou alguma API, que possa fazer sistema de pagamentos, não precisa ser com PIX, posso ser tambem com Bitcoin, mas só queria fazer um sistema de pagamento para poder incrementar meu portifólio e quando surgi alguma oportunidade onde eu devo usar um payment system, eu possa já estar preparado, mas enfim? qual outra biblioteca python eu posso ultilizar para fazer isso? além dessa, é claro.

**Comment by andreroggeri** [comment]
Sinceramente não acho que usar APIs não oficiais seja uma boa idéia para esse tipo de projeto. De um dia para o outro a API pode mudar ou ser bloqueada (como aconteceu aqui) e seu projeto vai morrer.

A unica API voltado para pagamentos que eu já mexi é a mercado pago, que obviamente vai cobrar a sua taxa em troca do serviço.
