### ISSUE TITLE
Por que não Pipenv?

### ISSUE THREAD

**Issue by julianolf** [andreroggeri/pynubank#46]
Resolvi abrir essa issue com uma pergunta pois sei que nem todo desenvolvedor Python simpatiza com a ferramenta. Eu pessoalmente não consigo me imaginar iniciando um projeto novo hoje sem utilizar o [Pipenv](http://pipenv.readthedocs.io/).

Os principais pontos que somam em sua utilização na minha opinião são:

- Simplicidade e consistência na gestão de dependências;
- Simplicidade na criação e manutenção de ambientes virtuais Python;
- Possibilidade de criar "alias" e automatizar a execução de comandos verbosos e tediosos;
- Permitir rodar comandos dentro do ambiente virtual Python sem precisar carregá-lo antes.

Esses são alguns dos pontos. Na página inicial do projeto tem mais detalhes de como funciona, quais as razões de se substituir os famosos `requirements.txt`, etc.

Se vocês acharem interessante eu posso enviar um PR substituindo os arquivos **requirements** pelo **Pipfile**. 🙂

**Comment by andreroggeri** [comment]
Fala @julianolf !

Ainda não conhecia o Pipenv 😄 

Ele parece ser bem interessante, mas não vi ganhos ao adicionar nesse projeto em específico. Seria apenas uma dependência a mais.


Mas continuo aberto a discussão caso eu não esteja vendo algo

**Comment by julianolf** [comment]
@andreroggeri, como eu havia comentado nem todo mundo gosta, ou conhece, e acho que é o tipo de ferramenta que você percebe as vantagens só quando começa a utilizar.

Eu não vejo como mais uma dependência, na verdade o Pipenv unifica em uma só ferramenta os recursos do pip, virtualenv e virtualenvwrapper trazendo ainda mais funcionalidades que estes juntos não possuem. Mas não consigo descrever as diferenças e vantagens sem um texto longo e sem parecer que estou evangelizando. 😆

De qualquer forma, já que não conhece o melhor é manter o projeto como está, e se um dia vier a testar e achar que vale a pena pode substituir os arquivos _requirements_ e gerar os _Pipfiles_.

**Comment by andreroggeri** [comment]
Acho super válido a discussão.
Inclusive estou começando um outro projeto e já quero experimentar pra poder falar com mais propriedade.

Tem muita ferramenta boa por aí.


Vou deixar a issue aberta por enquanto, pra ver se aparece mais alguém.

**Comment by julianolf** [comment]
> Tem muita ferramenta boa por aí.

Vou aproveitar e comentar. Um serviço e uma outra ferramenta para projetos em Python que tenho usado e gostado.
 - [PyUp](https://pyup.io) - atualização automática de dependências. Também tem o [Dependabot](http://dependabot.com/) que suporta outras linguagens.
 - [Black](https://black.readthedocs.io/en/stable/) - formatação de código. Adiciono como uma regra de pre-commit. Costumo executo no CI também para o caso de alguém esquecer de instalar  a regra de pre-commit.

**Comment by andreroggeri** [comment]
O PyUp já está configurado aqui no repo ! ⚙️ 

Sobre o Black eu só tenho um probleminha com as aspas, que por padrão são duplas do black (E não configuráveis) e eu gosto (Sim, isso é questão de gosto kkkk) das aspas simples, se não fosse por isso eu topava ele

**Comment by julianolf** [comment]
> Sobre o Black eu só tenho um probleminha com as aspas, que por padrão são duplas do black (E não configuráveis) e eu gosto (Sim, isso é questão de gosto kkkk) das aspas simples, se não fosse por isso eu topava ele

Eu te entendo, também preferia aspas simples só por não precisar pressionar duas teclas do teclado (e porque já utilizei linguagens em que elas possuem diferença). Quanto a configuração, no começo eu usava o parâmetro `-S, --skip-string-normalization` do Black por conta disso, mas depois de um tempo como a maioria das pessoas preferiam usar duplas para tudo eu acabei me adaptando.

**Comment by gchamon** [comment]
Pipenv acho indispensável. Já integra com as principais IDEs. Gera um custo de manutenção a mais, mas ele mesmo contorna, pq vc deve manter o pip mais atualizado (já tive problemas com o instalador do pipenv que não funcionava com a versão do pip do sistema).

Problema maior q vejo eh integrar o pipfile com setuptools pra centralizar as dependências.

**Comment by julianolf** [comment]
@gchamon no passado o Pipenv gerou algumas dores de cabeça por conta da versão do Pip mesmo, também passei por isso, acabei me acostumando a usar sempre a versão mais atual.

Sobre a integração com setuptools, eu particularmente prefiro que o setup para packaging e o gerenciamento das dependências para ambiente de desenvolvimento sejam coisas isoladas, mas é algo bem pessoal. 🙂

Se quiser dar uma olhada em alternativas, se já não o fez, da uma olhada nesta [thread](https://github.com/pypa/pipenv/issues/209).

**Comment by gchamon** [comment]
@julianolf bem legal essa issue! eu curto sincronizar o setuptools e o pipfile pra garantir que to rodando as mesmas versões sobre as quais desenvolvo, por isso comentei, valeu!

**Comment by gzamboni** [comment]
Como eu procuro sempre distribuir as lib no pypi, eu sempre sigo o https://packaging.python.org/tutorials/packaging-projects/
setuptools e pipfile... 
Nada contra pipenv ou conda.. mas isso limita quando a intenção é distribuir o app nos canais de distribuição do python.

**Comment by ianliu** [comment]
Se o objetivo é facilitar a distribuição do pacote, tem o Python Poetry (https://python-poetry.org/)
