### ISSUE TITLE
Acesso por QRCode descontinuado?

### ISSUE THREAD

**Issue by lpsouza** [andreroggeri/pynubank#461]
Estava tentando configurar o acesso por qrcode e notei que o app não tem mais a opção de ler o qrcode, pois eles encerraram o uso da aplicação pela web: https://blog.nubank.com.br/login-nubank-site/

Alguém já tentou montar esse acesso de outra forma? Ou e o fim do qrcode? 😬

**Comment by ceifa** [comment]
Mesma experiência aqui 🥲

**Comment by lucasgr7** [comment]
Acho que agora essa biblioteca foi de fim, estou tomando 403 de não autorizado nas requisições de cartão de crédito

**Comment by andreroggeri** [comment]
Infelizmente :/
