### ISSUE TITLE
Transactions não mostra as compras no débito

### ISSUE THREAD

**Issue by maronezzi** [andreroggeri/pynubank#59]
Alguém conseguiu acessar as compras de débito na conta corrente? Para mim na lista das transactions não aparece estes débitos.

**Comment by andreroggeri** [comment]
Oi @maronezzi blz ?

Qual método vc tá usando pra recuperar as informações ?

**Comment by maronezzi** [comment]
@andreroggeri  blza, 

Quando chamo esta linha de comando:
`transactions = filter_transactionsAccount(nu.get_account_statements(), STARTING_POINT)`

todos os itens que ele retorna, não aparecem as compras no débito.

![Captura de tela de 2019-06-28 13-58-57](https://user-images.githubusercontent.com/407525/60358634-0132a900-99ad-11e9-9165-8b5b86b5f775.png)

Entre os itens 5 e 6, tiveram 3 compras no débito.

**Comment by andreroggeri** [comment]
Faz sentido...
Consegue chamar o método `get_account_feed` e ver se ele retorna essa informação e se realmente é `DebitPurchaseEvent` ? 
Se for já subo uma correção com isso

**Comment by maronezzi** [comment]
Já fiz, é esse mesmo o problema, agora ele retorna:

![Captura de tela de 2019-06-28 14-43-37](https://user-images.githubusercontent.com/407525/60360961-507bd800-99b3-11e9-9f0a-256a4c1cf062.png)

o dict dele é diferente dos demais typename
![Captura de tela de 2019-06-28 14-44-10](https://user-images.githubusercontent.com/407525/60360970-55408c00-99b3-11e9-9219-413b617e5091.png)


Obrigado @andreroggeri

**Comment by Lrcezimbra** [comment]
Mesmo erro aqui, com o `get_account_feed` funciona :+1:

**Comment by rvogel** [comment]
Pessoal, acredito que o método `get_account_statements` não está retornando transações PIX.

**Comment by andreroggeri** [comment]
Vc pode olhar a #213 para um workaround

Em dom., 14 de mar. de 2021 17:38, Rafael Vogel de Oliveira <
***@***.***> escreveu:

**Comment by rvogel** [comment]
Pessoal estou tentando fazer meu sistema pessoal financeiro. Porém, o extrato da NuConta, não vêm com valores positivos e negativos.

Consegui buscar todo o extrato desde o 1º dia, e estou tentando definir o que são entradas e saídas baseado no campo `__typename`, que me entrega os seguintes resultados:


`01) DebitPurchaseReversalEvent
02) DebitWithdrawalReversalEvent
03) RemoveFromReserveEvent
04) ScheduledBarcodePaymentRequestFailedEvent
05) TransferInEvent
06) TransferOutReversalEvent

07) AddToReserveEvent
08) BarcodePaymentEvent
09) BillPaymentEvent
10) DebitPurchaseEvent
11) DebitWithdrawalEvent
12) DebitWithdrawalFeeEvent
13) DebitWithdrawalFeeReversalEvent
14) GenericFeedEvent
15) TransferOutEvent`

O primeiro grupo (01 à 06) eu assumi como sendo entradas (+) e o segundo grupo (07 à 15) como saídas (-). Porém a soma não resulta no saldo correto. Alguma sugestão?

**Comment by andreroggeri** [comment]
@rvogel no caso do GenericFeedEvent pode ser + ou - (Transferencias pix estão caindo nesse caso), talvez isso ajude a chegar mais próximo ao saldo.

Outro ponto é que os rendimentos da NuConta não são contabilizados nas transações

**Comment by andreroggeri** [comment]
Não, nunca consegui fazer bater...rs

Esses eventos não seriam da parte de "dinheiro guardado" ? Tem a #218 que fala justamente sobre fazer o saldo bater, e aparentemente é um problema geral :cry:
