### ISSUE TITLE
Problema com autenticação utilizando refresh_token

### ISSUE THREAD

**Issue by eulercosta** [andreroggeri/pynubank#61]
Ao me autenticar com CPF / Senha obtenho o access_token normalmente, mas o retorno do refresh_token é "string token". Dessa forma, só consigo me autenticar com o QRCode.

Além disso tive que comentar a linha: "self.refresh_token = auth_data['refresh_token']", pois estava dando 'Key Error' no "refresh_token".

Realmente as requisições não estão mais retornando o 'refresh_token'? Todas as vezes que eu precisar fazer uma requisição precisarei utilizar o QRCode?

**Comment by Lrcezimbra** [comment]
Mesmo KeyError do refresh_token aqui:

```
Traceback (most recent call last):
  File "/home/lucas/Projects/cronjobs/nubank_spreadsheet/__main__.py", line 118, in <module>
    main(initial_date)
  File "/home/lucas/Projects/cronjobs/nubank_spreadsheet/__main__.py", line 31, in main
    nubank.authenticate_with_qr_code(NUBANK_CPF, NUBANK_PASSWORD, uuid)
  File "/home/lucas/Projects/cronjobs/.venv/src/pynubank/pynubank/nubank.py", line 113, in authenticate_with_qr_code
    self.refresh_token = auth_data['refresh_token']
KeyError: 'refresh_token'
```

**Comment by andreroggeri** [comment]
Infelizmente parece que o Nubank parou de enviar essa informação ! 😢 

Então enquanto não acharmos um outro caminho, somente login com QRCode (assim como é no site)

O que podemos tentar é fazer o login novamente com o próprio token normal

**Comment by RNT17** [comment]
Estou tentando fazer somente o import 'from pynubank import Nubank' e retorna o erro:

<code>
Traceback (most recent call last):
  File "nubank.py", line 1, in <module>
    from pynubank import Nubank
  File "/home/rnt/.local/lib/python2.7/site-packages/pynubank/__init__.py", line 1, in <module>
    from .nubank import Nubank, NuException
  File "/home/rnt/.local/lib/python2.7/site-packages/pynubank/nubank.py", line 7, in <module>
    from pynubank import utils
  File "/home/rnt/.local/lib/python2.7/site-packages/pynubank/utils.py", line 4
    def print_qr_code(uuid: str):
                          ^
SyntaxError: invalid syntax
</code>

**Comment by andreroggeri** [comment]
Vi que você tá usando o Python 2.7
Por ser uma versão antiga que está sendo descontinuada, creio que não valha o esforço para ser retrocompatível.
Você não consegue utilizar o Python 3 ?

**Comment by RNT17** [comment]
Ok. Instalei Python3, no arquivo só faço o import 'from pynubank import Nubank'
Rodo o python3 nubank.py e agora me retorna:

<code>
Traceback (most recent call last):
  File "nubank.py", line 1, in <module>
    from pynubank import Nubank
ImportError: No module named 'pynubank'
</code>

**Comment by RNT17** [comment]
Obrigado. Perfeito era a versão do Python. Atualmente o Nubank só disponibiliza saldo e históricos?

**Comment by andreroggeri** [comment]
Isso @RNT17. O que vc está procurando ?

**Comment by RNT17** [comment]
Uma forma de programar transferências.

**Comment by andreroggeri** [comment]
Acredito que isso esteja fora do escopo dessa lib, tanto por questões de segurança (Seria uma enorme responsabilidade fazer isso direito) quanto por utilizarmos as APIs do Nubank de forma não oficial (A qualquer momento o Nubank pode cortar o acesso, mudar o contrato de API)

**Comment by andreroggeri** [comment]
Closed by #71

**Comment by andreroggeri** [comment]
@eulercosta Removi a funcionalidade de autenticação por refresh_token e estou publicando a 1.0.0 com essas alterações
