### ISSUE TITLE
Cuidado ao bumpar minor versions

### ISSUE THREAD

**Issue by Lrcezimbra** [andreroggeri/pynubank#63]
Estava usando a versão anterior que a autenticação com QR Code era assim:
```
nubank = Nubank(NUBANK_CPF, NUBANK_PASSWORD, allow_qr_code_auth=True)
```
daí atualizei a versão pensando que não tinha nenhuma breaking change, dado que foi um minor version, mas a vi que a autenticação via QR Code está completamente diferente, quebrando meu serviço:
```
nubank = Nubank()
uuid, qr_code = nubank.get_qr_code()
qr_code.print_ascii(invert=True)
input('Após escanear o QRCode pressione enter para continuar')
nubank.authenticate_with_qr_code(NUBANK_CPF, NUBANK_PASSWORD, uuid)
```

Então deixo minha sugestão/pedido de usarmos [Semantic Versioning](https://semver.org/) e atualizar a major version quando a modificação quebrar a retrocompatibilidade.

**Comment by andreroggeri** [comment]
Fala @Lrcezimbra blz ?

A última versão publicada no PyPi (0.19) mantém o comportamento descrito por vc...

O código da master realmente é uma breaking change, tanto que salta da versão 0.19 para a versão 1.0.0 (Mas a 1.0.0 ainda não está no PyPi).

Vc pode confirmar de qual versão vc saiu e para qual vc foi que deu ruim ?

**Comment by Lrcezimbra** [comment]
Ah sim, realmente estou usando a versão q está na master, pensei q fosse a última do PyPi, confusão minha. Obrigado pelo esclarecimento e desculpa a confusão. Vou fechar a issue.

**Comment by Lrcezimbra** [comment]
@andreroggeri outra sugestão então :smile: poderíamos deixar a master com o q está no PyPi e criar uma branch `develop` para as próximas versões, creio q ficaria mais organizado e mais fácil para criar hotfixes como o #63 e #64

**Comment by andreroggeri** [comment]
Concordo com a sugestão, assim quem vier aqui olhar o README, vai ver a documentação referente a versão que está no PyPi.

E também acho que precisamos de um contributing pra explicar isso ! 👍
