### ISSUE TITLE
AttributeError: 'str' object has no attribute 'uuid4'

### ISSUE THREAD

**Issue by allangarcia** [andreroggeri/pynubank#92]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f085a5a0ac0c> in <module>
      1 # Utilize o CPF sem pontos ou traços
      2 nu = Nubank()
----> 3 uuid, qr_code = nu.get_qr_code()
      4 #nu.authenticate_with_qr_code('REDACTED', 'REDACTED', uuid)
      5 qr_code.print_ascii(invert=True)

<ipython-input-1-731b9241ff83> in get_qr_code(self)
     86 
     87     def get_qr_code(self) -> Tuple[str, QRCode]:
---> 88         content = str(uuid.uuid4())
     89         qr = QRCode()
     90         qr.add_data(content)

AttributeError: 'str' object has no attribute 'uuid4'

**Comment by allangarcia** [comment]
Isso é um bug ou eu estou fazendo algo errado? Estou usando o Jupyter Notebook para rodar o código.

**Comment by andreroggeri** [comment]
Fala @allangarcia, você tá usando qual versão do python ?

**Comment by allangarcia** [comment]
Python 3

--
Allan Garcia

**Comment by andreroggeri** [comment]
Acabei de rodar aqui no Jupyter e consegui gerar o QRCode
![image](https://user-images.githubusercontent.com/6232673/72435276-75cc0a00-377c-11ea-9177-0a94da6a1fe7.png)

Minhas versões:

Python 3.7.3
pynubank-1.0.1
qrcode-6.1

**Comment by allangarcia** [comment]
Vou ver sem tem algum problema no meu ambiente. Obrigado. 

--
Allan Garcia

**Comment by andreroggeri** [comment]
Vc consegue fazer o seguinte teste:

```
from uuid import uuid4
print(uuid4)
print(str(uuid4))
```

**Comment by andreroggeri** [comment]
Na última versão do pynubank não temos mais QRCode, então esse problema deixa de existir 🙏
