### ISSUE TITLE
Acesso com QR Code retornando erro

### ISSUE THREAD

**Issue by jeffersonmsb** [andreroggeri/pynubank#94]
Olá, hj fui atualizar minhas contas e o tive o erro 403 retornado após o pynubank pedir o QR Code.

Fui acessar pelo site e notei que o QR Code não é mais pedido.

Antes havia um método na biblioteca para acesso sem QR Code, ainda não testei se esse método voltou a funciona.

^^

**Comment by rodrigomideac** [comment]
Opa, mesma coisa aqui! Dando um `try catch` na exceção acaba tendo isso na response:
`{'error': 'Forbidden'}`

**Comment by rodrigomideac** [comment]
Notei que o request do _password_auth basta pra logar, se quiserem testem essa função

```python
    def authenticate(self, cpf: str, password):
        auth_data = self._password_auth(cpf, password)
        self.headers['Authorization'] = f'Bearer {auth_data["access_token"]}'
        self.feed_url = auth_data['_links']['events']['href']
        self.query_url = auth_data['_links']['ghostflame']['href']
        self.bills_url = auth_data['_links']['bills_summary']['href']
```

Será que tiraram o QR code definitivamente? Teria que abrir um PR pra mudar os testes também.

**Comment by jeffersonmsb** [comment]
Eu usei o método antigo pra logar, antes desse do QR.

Notei também que alguns campos de alguns tipos transação da nuconta não existem mais. Como o _amout_ em transações de compra no débito.

**Comment by andreroggeri** [comment]
Voltamos ao processo antigo então.. haha

Bom, eu ainda não fiz o teste, mas hoje a noite vou tentar validar e remover a funcionalidade do QRCode

**Comment by andreroggeri** [comment]
Deu bom... É basicamente o código do @rodrigomideac ...
Assim que eu ajustar o README e os testes já publico uma versão nova 🙏
