### ISSUE TITLE
Autenticação com QRCode voltou a ser obrigatória

### ISSUE THREAD

**Issue by cleberhenriques** [andreroggeri/pynubank#97]
Boa tarde pessoal, tudo bem?

Passando aqui só para avisar que a autenticação com QRCode voltou a ser necessária para fazer autenticação.  Parece que é algo bem recente, pois na terça-feira estava funcionando sem a necessidade do QRCode.

Acredito que seria melhor deixar as duas formas de autenticação no Pynubank, para poder alternar entre elas sem precisar alterar o código.

Abraço!

**Comment by andreroggeri** [comment]
Pô Nubank... 😢 

Acho que o mais fácil é voltar o repo pra tag 1.0.1 e deixar o método de login com senha público.

Daí quem for usar testa um ou o outro pra saber qual que tá funcionando.

**Comment by cleberhenriques** [comment]
Testei com a versão 1.0.1 e tá dando 404 quando tenta autenticar pegando a url 'lift' da lista.
Quando tiver mais tempo vou tentar investigar.

**Comment by andreroggeri** [comment]
Aqui rolou ao voltar pra 1.0.1.
Vou soltar uma nova versão com as duas opções
